function result = s12_run_transient_wave_fvm(config)
%S12_RUN_TRANSIENT_WAVE_FVM Run controlled PP FVM transient-wave model.
arguments
    config (1,1) struct
end
validateConfig(config);
root = fileparts(fileparts(fileparts(mfilename("fullpath"))));
modelPath = fullfile(root, "models", "fvm_ref", ...
    "s12_euler_fvm_transient_wave_ref.slx");
if ~isfile(modelPath)
    error("S12:TransientWave:MissingModel", "Controlled transient FVM model is missing.");
end
benchmarkRoot = fullfile(root, "benchmark");
if ~any(string(strsplit(path, pathsep)) == benchmarkRoot)
    addpath(benchmarkRoot);
    pathCleanup = onCleanup(@() rmpath(benchmarkRoot));
else
    pathCleanup = onCleanup(@() []);
end
modelName = "s12_euler_fvm_transient_wave_ref";
wasLoaded = bdIsLoaded(modelName);
load_system(modelPath);
modelCleanup = onCleanup(@() closeIfOwned(modelName, wasLoaded));
cellCount = size(config.initial_state, 2);
ambient = config.ambient_state;
buffer = repmat(ambient, 1, 800);
buffer(:, 1:cellCount) = config.initial_state;
workspace = get_param(modelName, "ModelWorkspace");
setValue(workspace, "S12_Wave_State", buffer);
setValue(workspace, "S12_Wave_AmbientState", ambient);
setValue(workspace, "S12_Wave_Gamma", config.gamma);
setValue(workspace, "S12_Wave_Dx", config.pipe_length_m / cellCount);
setValue(workspace, "S12_Wave_EndTime", config.end_time_s);
setValue(workspace, "S12_Wave_CFL", config.cfl);
setValue(workspace, "S12_Wave_MaxSteps", config.max_steps);
setValue(workspace, "S12_Wave_RhoFloor", config.rho_floor);
setValue(workspace, "S12_Wave_PFloor", config.p_floor);
setValue(workspace, "S12_Wave_CFLHardMax", config.cfl_hard_maximum);
setValue(workspace, "S12_Wave_LeftBoundaryMode", boundaryMode(config.left_boundary));
setValue(workspace, "S12_Wave_RightBoundaryMode", boundaryMode(config.right_boundary));
setValue(workspace, "S12_Wave_DarcyFriction", config.darcy_friction_factor);
setValue(workspace, "S12_Wave_HydraulicDiameter", config.hydraulic_diameter_m);
setValue(workspace, "S12_Wave_ActiveCellCount", cellCount);
output = sim(modelName, "StopTime", "0");
finalBuffer = output.get("S12_WaveFinalState");
diagnostics = output.get("S12_WaveQualificationDiagnostics");
stepCount = scalarValue(output.get("S12_WaveStepCount"));
traceCount = stepCount + 1;
result = struct( ...
    "final_state", finalBuffer(:, 1:cellCount), ...
    "final_time_s", scalarValue(output.get("S12_WaveFinalTime")), ...
    "step_count", stepCount, ...
    "maximum_cfl", scalarValue(output.get("S12_WaveMaxCourant")), ...
    "conservation_residual", vectorValue(output.get("S12_WaveConservationResidual")), ...
    "boundary_energy_flux", vectorValue(output.get("S12_WaveBoundaryEnergyFlux"), traceCount), ...
    "trace_time_s", vectorValue(output.get("S12_WaveTraceTime"), traceCount), ...
    "trace_pressure_pa", matrixValue(output.get("S12_WaveTracePressure"), traceCount), ...
    "trace_velocity_mps", matrixValue(output.get("S12_WaveTraceVelocity"), traceCount), ...
    "probe_locations_m", probeLocations(config.pipe_length_m, cellCount), ...
    "model_path", modelPath, ...
    "qualification", qualification(diagnostics, config, cellCount));
clear modelCleanup pathCleanup
end

function validateConfig(config)
required = ["gamma", "pipe_length_m", "initial_state", "ambient_state", ...
    "end_time_s", "cfl", "max_steps", "rho_floor", "p_floor", ...
    "cfl_hard_maximum", "left_boundary", "right_boundary", ...
    "darcy_friction_factor", "hydraulic_diameter_m"];
if ~isstruct(config) || ~all(isfield(config, required)) || ...
        size(config.initial_state, 1) ~= 3 || size(config.initial_state, 2) < 3 || ...
        size(config.initial_state, 2) > 800 || ~isequal(size(config.ambient_state), [3, 1]) || ...
        config.gamma <= 1 || config.pipe_length_m <= 0 || config.end_time_s < 0 || ...
        config.cfl <= 0 || config.cfl > config.cfl_hard_maximum || ...
        config.max_steps < 1 || config.max_steps > 4095 || config.rho_floor <= 0 || ...
        config.p_floor <= 0 || config.darcy_friction_factor < 0 || ...
        config.hydraulic_diameter_m <= 0 || any(~isfinite(config.initial_state), "all") || ...
        any(~isfinite(config.ambient_state), "all")
    error("S12:TransientWave:InvalidInput", "Invalid transient FVM configuration.");
end
if any(config.initial_state(1, :) < config.rho_floor) || ...
        any(pressure(config.initial_state, config.gamma) < config.p_floor)
    error("S12:TransientWave:InvalidInput", "Initial transient state violates floors.");
end
boundaryMode(config.left_boundary);
boundaryMode(config.right_boundary);
end

function mode = boundaryMode(id)
id = string(id);
switch id
    case "closed_rigid_end"
        mode = 1;
    case "ideal_pressure_release_open_end"
        mode = 2;
    case "nonreflecting_reference_boundary"
        mode = 3;
    otherwise
        error("S12:TransientWave:InvalidBoundary", ...
            "Unknown transient validation boundary '%s'.", id);
end
end

function value = pressure(state, gamma)
density = state(1, :);
velocity = state(2, :) ./ density;
value = (gamma - 1) * (state(3, :) - 0.5 * density .* velocity.^2);
end

function setValue(workspace, name, value)
parameter = workspace.getVariable(name);
if isa(parameter, "Simulink.Parameter")
    parameter.Value = value;
    workspace.assignin(name, parameter);
else
    workspace.assignin(name, value);
end
end

function value = scalarValue(raw)
value = raw(end);
end

function value = vectorValue(raw, count)
if nargin < 2
    count = numel(raw);
end
value = reshape(raw, 1, []);
value = value(1:count);
end

function value = matrixValue(raw, count)
value = raw(:, 1:count);
end

function value = probeLocations(lengthM, cellCount)
indices = [max(1, round(0.25 * (cellCount + 1))), ...
    max(1, round(0.50 * (cellCount + 1))), ...
    min(cellCount, max(1, round(0.75 * (cellCount + 1))))];
value = (indices - 0.5) * lengthM / cellCount;
end

function value = qualification(diagnostics, config, cellCount)
d = reshape(diagnostics, 1, []);
value = struct( ...
    "spatial_scheme", "muscl_minmod_pp", ...
    "positivity_mode", "reconstruction_global_lf_flux_pp", ...
    "rho_floor", config.rho_floor, "p_floor", config.p_floor, ...
    "reconstruction_pp_activation_count", d(9), ...
    "flux_pp_activation_count", d(13), ...
    "reconstruction_pp_min_theta", d(12), "flux_pp_min_theta", d(16), ...
    "minimum_reconstructed_density", d(1), ...
    "minimum_reconstructed_pressure", d(2), ...
    "minimum_anchor_partial_density", d(17), ...
    "minimum_anchor_partial_pressure", d(18), ...
    "minimum_final_partial_density", d(19), ...
    "minimum_final_partial_pressure", d(20), ...
    "minimum_density", min(d(26:2:30)), ...
    "minimum_pressure", min(d(27:2:31)), ...
    "minimum_cell_density_by_stage", [d(26), d(28), d(30)], ...
    "minimum_cell_pressure_by_stage", [d(27), d(29), d(31)], ...
    "minimum_interface_density_by_stage", d(32:34), ...
    "minimum_interface_pressure_by_stage", d(35:37), ...
    "minimum_anchor_partial_density_by_stage", d(38:40), ...
    "minimum_anchor_partial_pressure_by_stage", d(41:43), ...
    "minimum_final_partial_density_by_stage", d(44:46), ...
    "minimum_final_partial_pressure_by_stage", d(47:49), ...
    "invalid_reconstruction_count", d(3), "invalid_stage_count", d(23), ...
    "retry_count", d(24), "rejected_step_count", d(25), ...
    "end_time_clipping_count", d(8), ...
    "limited_cell_fraction", d(10) / max(1, d(11)), ...
    "limiter_activation_count", d(4), ...
    "reconstruction_variables", "primitive_rho_u_p", "limiter", "minmod", ...
    "clipping_count", 0, "flux_fallback_count", 0, ...
    "maximum_flux_correction_norm", d(22), ...
    "active_cell_count", cellCount);
end

function closeIfOwned(modelName, wasLoaded)
if ~wasLoaded && bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
