function metrics = s12_transient_wave_reflection_metrics(time, pressure, ...
        velocity, windows)
%S12_TRANSIENT_WAVE_REFLECTION_METRICS Measure fixed-window wave evidence.
arguments
    time (1,:) double {mustBeFinite}
    pressure (1,:) double {mustBeFinite}
    velocity (1,:) double {mustBeFinite}
    windows (1,1) struct
end
if numel(time) < 2 || numel(time) ~= numel(pressure) || ...
        numel(time) ~= numel(velocity) || any(diff(time) <= 0)
    error("S12:TransientWave:InvalidTrace", ...
        "Reflection traces must be aligned and strictly increasing.");
end
required = ["incident", "reflected", "ambient_pressure", ...
    "ambient_density", "wave_speed"];
if ~all(isfield(windows, required)) || ...
        numel(windows.incident) ~= 2 || numel(windows.reflected) ~= 2 || ...
        windows.incident(1) >= windows.incident(2) || ...
        windows.reflected(1) >= windows.reflected(2) || ...
        windows.incident(2) >= windows.reflected(1) || ...
        windows.ambient_density <= 0 || windows.wave_speed <= 0
    error("S12:TransientWave:InvalidWindow", ...
        "Reflection windows must be separated, ordered, and physical.");
end
incidentMask = time >= windows.incident(1) & time <= windows.incident(2);
reflectedMask = time >= windows.reflected(1) & time <= windows.reflected(2);
if sum(incidentMask) < 2 || sum(reflectedMask) < 2
    error("S12:TransientWave:InvalidWindow", ...
        "Each fixed reflection window needs at least two samples.");
end
pressurePerturbation = pressure - windows.ambient_pressure;
incidentPressure = signedPeak(pressurePerturbation(incidentMask));
reflectedPressure = signedPeak(pressurePerturbation(reflectedMask));
incidentVelocity = signedPeak(velocity(incidentMask));
reflectedVelocity = signedPeak(velocity(reflectedMask));
if incidentPressure == 0 || incidentVelocity == 0
    error("S12:TransientWave:NoIncidentWave", ...
        "Reflection coefficients require a nonzero incident wave.");
end
impedance = windows.ambient_density * windows.wave_speed;
incidentEnergy = trapz(time(incidentMask), ...
    pressurePerturbation(incidentMask).^2 / impedance);
reflectedEnergy = trapz(time(reflectedMask), ...
    pressurePerturbation(reflectedMask).^2 / impedance);
metrics = struct( ...
    "pressure_reflection_coefficient", reflectedPressure / incidentPressure, ...
    "velocity_reflection_coefficient", reflectedVelocity / incidentVelocity, ...
    "incident_energy", incidentEnergy, ...
    "reflected_energy", reflectedEnergy, ...
    "transmitted_energy", 0, ...
    "boundary_energy_residual", abs(incidentEnergy - reflectedEnergy) / ...
        max(incidentEnergy, realmin));
end

function value = signedPeak(signal)
[~, index] = max(abs(signal));
value = signal(index);
end
