function reference = s12_transient_wave_linear_reference(definition, position, time, component)
%S12_TRANSIENT_WAVE_LINEAR_REFERENCE Evaluate the frozen small-signal wave.
arguments
    definition (1,1) struct
    position (1,:) double {mustBeFinite}
    time (1,1) double {mustBeNonnegative, mustBeFinite}
    component (1,1) string {mustBeMember(component, ...
        ["incident", "closed_rigid_reflected", ...
        "ideal_pressure_release_reflected"])}
end
validateDefinition(definition);
waveSpeed = sqrt(definition.gamma * definition.ambient_pressure / ...
    definition.ambient_density);
switch component
    case "incident"
        center = definition.pulse_center + waveSpeed * time;
        pressureSign = 1;
        velocitySign = 1;
    case "closed_rigid_reflected"
        center = 2 * definition.pipe_length - definition.pulse_center - ...
            waveSpeed * time;
        pressureSign = 1;
        velocitySign = -1;
    case "ideal_pressure_release_reflected"
        center = 2 * definition.pipe_length - definition.pulse_center - ...
            waveSpeed * time;
        pressureSign = -1;
        velocitySign = 1;
end
shape = exp(-0.5 * ((position - center) / definition.pulse_sigma).^2);
pressurePerturbation = pressureSign * definition.pressure_amplitude * shape;
velocityPerturbation = velocitySign * pressurePerturbation / ...
    (definition.ambient_density * waveSpeed);
densityPerturbation = pressurePerturbation / waveSpeed^2;
reference = struct( ...
    "reference_id", "linear_gaussian_acoustics.v1", ...
    "wave_speed", waveSpeed, ...
    "pressure_perturbation", pressurePerturbation, ...
    "velocity_perturbation", velocityPerturbation, ...
    "density_perturbation", densityPerturbation, ...
    "pressure", definition.ambient_pressure + pressurePerturbation, ...
    "density", definition.ambient_density + densityPerturbation, ...
    "component", component);
end

function validateDefinition(definition)
required = ["gamma", "ambient_density", "ambient_pressure", ...
    "pipe_length", "pulse_center", "pulse_sigma", "pressure_amplitude"];
if ~all(isfield(definition, required))
    error("S12:TransientWave:InvalidDefinition", ...
        "The linear-wave definition is incomplete.");
end
values = cell2mat(cellfun(@(field) definition.(field), ...
    cellstr(required), "UniformOutput", false));
if ~isreal(values) || any(~isfinite(values)) || definition.gamma <= 1 || ...
        any(values(2:end) <= 0) || definition.pulse_center >= definition.pipe_length
    error("S12:TransientWave:InvalidDefinition", ...
        "The linear-wave definition is nonphysical.");
end
if abs(definition.pressure_amplitude) / definition.ambient_pressure > 0.01
    error("S12:TransientWave:OutsideLinearRegime", ...
        "The pressure perturbation exceeds the frozen 1 percent linear limit.");
end
end
