function result = s12_radiation_boundary_step_stability(package, dt)
%S12_RADIATION_BOUNDARY_STEP_STABILITY Measure SSP-RK3 state-space stability.
arguments
    package (1,1) struct
    dt (1,1) double {mustBeFinite, mustBeGreaterThan(dt, 0)}
end
if ~isfield(package, "state_space_A") || ...
        ~isequal(size(package.state_space_A), [2, 2]) || ...
        any(~isfinite(package.state_space_A), "all")
    error("S12:Radiation:InvalidState", ...
        "Radiation package must contain a finite two-state A matrix.");
end
poles = eig(package.state_space_A);
staticLimit = isStaticLimit(package);
continuousStable = staticLimit || all(real(poles) < 0);
if ~continuousStable
    error("S12:Radiation:UnstableStateSpace", ...
        "Radiation boundary package has a non-decaying continuous-time pole.");
end
z = dt * poles;
amplification = abs(1 + z + 0.5 * z.^2 + z.^3 / 6);
result = struct( ...
    "continuous_poles", poles, ...
    "continuous_stable", continuousStable, ...
    "static_limit", staticLimit, ...
    "time_step_s", dt, ...
    "stage_pole_amplification", amplification, ...
    "maximum_stage_pole_amplification", max(amplification), ...
    "stability_polynomial_id", "ssprk3_taylor_3.v1");
end

function value = isStaticLimit(package)
value = isfield(package, "state_space_B") && isfield(package, "state_space_C") && ...
    isequal(size(package.state_space_B), [2, 1]) && ...
    isequal(size(package.state_space_C), [1, 2]) && ...
    all(package.state_space_A == 0, "all") && ...
    all(package.state_space_B == 0, "all") && ...
    all(package.state_space_C == 0, "all");
end
