function result = s12_radiation_time_domain_reference(package, time, outgoingPressure)
%S12_RADIATION_TIME_DOMAIN_REFERENCE Independently integrate frozen R(s).
arguments
    package (1,1) struct
    time (1,:) double {mustBeFinite}
    outgoingPressure (1,:) double {mustBeFinite}
end
validateInputs(package, time, outgoingPressure);
state = zeros(2, numel(time));
if isfield(package, "initial_state")
    state(:, 1) = package.initial_state;
end
incoming = zeros(size(time));
incoming(1) = package.state_space_C * state(:, 1) + ...
    package.state_space_D * outgoingPressure(1);
for index = 1:(numel(time) - 1)
    dt = time(index + 1) - time(index);
    augmentedTransition = expm([package.state_space_A, package.state_space_B; ...
        zeros(1, 3)] * dt);
    transition = augmentedTransition(1:2, 1:2);
    inputMap = augmentedTransition(1:2, 3);
    state(:, index + 1) = transition * state(:, index) + ...
        inputMap * outgoingPressure(index);
    incoming(index + 1) = package.state_space_C * state(:, index + 1) + ...
        package.state_space_D * outgoingPressure(index + 1);
end
result = struct( ...
    "time_s", time, ...
    "outgoing_pressure_pa", outgoingPressure, ...
    "incoming_pressure_pa", incoming, ...
    "state", state, ...
    "reference_integrator_id", "matrix_exponential_zoh_independent.v1");
end

function validateInputs(package, time, outgoingPressure)
required = ["state_space_A", "state_space_B", "state_space_C", "state_space_D"];
if ~all(isfield(package, required)) || numel(time) < 2 || ...
        numel(time) ~= numel(outgoingPressure) || ...
        any(diff(time) <= 0) || ~isequal(size(package.state_space_A), [2, 2]) || ...
        ~isequal(size(package.state_space_B), [2, 1]) || ...
        ~isequal(size(package.state_space_C), [1, 2]) || ...
        ~isequal(size(package.state_space_D), [1, 1])
    error("S12:Radiation:InvalidReferenceInput", ...
        "Reference requires strictly increasing time and the frozen two-state package.");
end
if isfield(package, "initial_state") && ...
        (~isequal(size(package.initial_state), [2, 1]) || ...
        any(~isfinite(package.initial_state)))
    error("S12:Radiation:InvalidReferenceInput", ...
        "Reference initial state must be finite two-state data.");
end
end
