function result = s12_radiation_unflanged_pade_fit(ka, definition)
%S12_RADIATION_UNFLANGED_PADE_FIT Evaluate published causal (1,2) candidate.
arguments
    ka {mustBeNumeric, mustBeReal, mustBeFinite}
    definition (1,1) struct
end
ka = reshape(double(ka), 1, []);
if any(abs(ka) >= definition.plane_wave_cutoff_ka)
    error("S12:Radiation:PlaneWaveCutoff", ...
        "The plane-wave candidate rejects abs(ka) >= %.12g.", ...
        definition.plane_wave_cutoff_ka);
end
n1 = 0.167;
d1 = 1.393;
d2 = 0.457;
scaledFrequency = 1i * ka;
reflection = -(1 + n1 * scaledFrequency) ./ ...
    (1 + d1 * scaledFrequency + d2 * scaledFrequency.^2);
impedance = s12_radiation_impedance_from_reflection(reflection, ...
    definition.rho0, definition.c0, definition.pipe_radius_m);
tau = definition.pipe_radius_m / definition.c0;
stateSpace = struct( ...
    "A", [0, 1; -1 / (d2 * tau^2), -d1 / (d2 * tau)], ...
    "B", [0; 1], ...
    "C", [-1 / (d2 * tau^2), -n1 / (d2 * tau)], ...
    "D", 0);
poles = eig(stateSpace.A);
if any(abs(ka) > definition.accepted_ka_band(2))
    applicability = "diagnostic_outside_fit_band";
else
    applicability = "accepted_fit_band";
end
result = struct( ...
    "ka", ka, ...
    "frequency_hz", ka * definition.c0 / (2 * pi * definition.pipe_radius_m), ...
    "reflection", reflection, ...
    "normalized_impedance", impedance.normalized_impedance, ...
    "impedance_pa_s_per_m3", impedance.impedance_pa_s_per_m3, ...
    "fit_order", [1, 2], ...
    "poles", poles, ...
    "stability_margin", -max(real(poles)), ...
    "state_space", stateSpace, ...
    "fit_band_ka", definition.accepted_ka_band, ...
    "fit_method_id", definition.fit_method_id, ...
    "applicability", applicability);
end
