function package = s12_radiation_boundary_package(definition)
%S12_RADIATION_BOUNDARY_PACKAGE Export a frequency-only Sprint 4D-A package.
arguments
    definition (1,1) struct
end
fit = s12_radiation_unflanged_pade_fit(definition.accepted_ka_band, definition);
payload = sprintf( ...
    'radiation_boundary_package.v1|%s|%s|%.17g|%.17g|%.17g|%.17g|%.17g', ...
    definition.radiation_geometry, definition.normalization_id, ...
    definition.accepted_ka_band(1), definition.accepted_ka_band(2), ...
    definition.pipe_radius_m, definition.rho0, definition.c0);
package = struct( ...
    "schema", "radiation_boundary_package.v1", ...
    "geometry", definition.radiation_geometry, ...
    "normalization", definition.normalization_id, ...
    "valid_ka_band", definition.accepted_ka_band, ...
    "sample_rate_constraints", "integration_deferred_to_sprint_4d_b", ...
    "state_space_A", fit.state_space.A, ...
    "state_space_B", fit.state_space.B, ...
    "state_space_C", fit.state_space.C, ...
    "state_space_D", fit.state_space.D, ...
    "initial_state", zeros(2, 1), ...
    "reference_plane", definition.reference_plane, ...
    "end_correction", definition.static_end_correction_over_radius, ...
    "passivity_evidence", "frequency_domain_contract_pending_benchmark", ...
    "fit_error_summary", "frequency_domain_contract_pending_benchmark", ...
    "source_commit", "runtime_provenance_added_by_benchmark", ...
    "asset_sha256", computeSha256(payload));
end

function value = computeSha256(payload)
digest = java.security.MessageDigest.getInstance("SHA-256");
digest.update(uint8(char(payload)));
bytes = typecast(digest.digest(), "uint8");
value = string(upper(reshape(dec2hex(bytes, 2).', 1, [])));
end
