function definition = s12_radiation_case_definition(profile)
%S12_RADIATION_CASE_DEFINITION Freeze Sprint 4D-A radiation contracts.
arguments
    profile (1,1) string {mustBeMember(profile, ["quick", "full"])}
end
if profile == "quick"
    acceptedKa = unique([logspace(log10(0.02), log10(0.2), 8), ...
        linspace(0.25, 2, 12)]);
else
    acceptedKa = unique([logspace(log10(0.02), log10(0.2), 32), ...
        linspace(0.21, 2, 96)]);
end
trainingKa = linspace(0, 3.832, 75);
validationKa = linspace(0.021, 1.979, 80);
similarityMappings = [ ...
    struct("pipe_radius_m", 0.010, "rho0", 1.18, "c0", 343), ...
    struct("pipe_radius_m", 0.020, "rho0", 0.98, "c0", 410), ...
    struct("pipe_radius_m", 0.035, "rho0", 1.32, "c0", 300)];
definition = struct( ...
    "profile", profile, ...
    "radiation_geometry", "circular_unflanged", ...
    "flange_condition", "unflanged", ...
    "mean_flow_mach", 0, ...
    "mode_id", "plane_wave", ...
    "time_harmonic_convention", "exp(+j*omega*t)", ...
    "impedance_definition", "pressure_over_volume_velocity", ...
    "normalization_id", "rho0_c0_over_area.v1", ...
    "reference_plane", "bore_end", ...
    "reference_method_id", "levine_schwinger_direct_quadrature.v1", ...
    "fit_method_id", "silva_2009_causal_pade_1_2.v1", ...
    "pipe_radius_m", 0.020, ...
    "rho0", 1.18, ...
    "c0", 343, ...
    "accepted_ka_band", [0.02, 2], ...
    "diagnostic_ka_band", [2, 3.832], ...
    "plane_wave_cutoff_ka", 3.832, ...
    "static_end_correction_over_radius", 0.6133, ...
    "accepted_ka", reshape(acceptedKa, 1, []), ...
    "fit_training_ka", reshape(trainingKa, 1, []), ...
    "fit_validation_ka", reshape(validationKa, 1, []), ...
    "similarity_mappings", similarityMappings, ...
    "accepted_features", ["frequency_domain_reference", ...
        "causal_state_space_candidate", "radiation_boundary_package"], ...
    "acceptance", acceptance());
end

function value = acceptance
value = struct( ...
    "quadrature_reflection_limit", 1e-9, ...
    "quadrature_end_correction_limit", 1e-8, ...
    "low_frequency_end_correction_abs_limit", 5e-3, ...
    "passivity_negative_tolerance", 1e-10, ...
    "reflection_magnitude_tolerance", 1e-10, ...
    "maximum_reflection_complex_error", 0.20, ...
    "rms_reflection_complex_error", 0.08, ...
    "maximum_reflection_magnitude_error", 0.08, ...
    "maximum_reflection_phase_error_rad", 0.20, ...
    "maximum_end_correction_relative_error", 0.08, ...
    "similarity_limit", 1e-10);
end
