function result = s12_radiation_boundary_stage(package, state, outgoingPressure, ...
        ambient, gamma, smallSignalLimit)
%S12_RADIATION_BOUNDARY_STAGE Evaluate one explicit radiation-boundary stage.
arguments
    package (1,1) struct
    state (:,1) double
    outgoingPressure (1,1) double {mustBeFinite}
    ambient (1,1) struct
    gamma (1,1) double {mustBeFinite, mustBeGreaterThan(gamma, 1)}
    smallSignalLimit (1,1) double {mustBeFinite, mustBeGreaterThan(smallSignalLimit, 0)}
end
validatePackage(package, state);
validateAmbient(ambient);
incomingPressure = package.state_space_C * state + ...
    package.state_space_D * outgoingPressure;
stateDerivative = package.state_space_A * state + ...
    package.state_space_B * outgoingPressure;
if ~isfinite(incomingPressure) || any(~isfinite(stateDerivative))
    error("S12:Radiation:InvalidState", ...
        "Radiation state-space evaluation produced a non-finite value.");
end
pressurePerturbation = outgoingPressure + incomingPressure;
if max(abs([outgoingPressure, incomingPressure, pressurePerturbation])) > ...
        smallSignalLimit * ambient.pressure_pa
    error("S12:Radiation:SmallSignalLimit", ...
        "Radiation boundary perturbation exceeds the configured small-signal limit.");
end
boundaryPressure = ambient.pressure_pa + pressurePerturbation;
boundaryDensity = ambient.density_kg_m3 + pressurePerturbation / ...
    ambient.sound_speed_mps^2;
boundaryVelocity = (outgoingPressure - incomingPressure) / ...
    (ambient.density_kg_m3 * ambient.sound_speed_mps);
if boundaryPressure <= 0 || boundaryDensity <= 0 || ...
        ~isfinite(boundaryVelocity)
    error("S12:Radiation:InvalidState", ...
        "Radiation boundary state is nonphysical; clipping is prohibited.");
end
result = struct( ...
    "state_derivative", stateDerivative, ...
    "outgoing_pressure_pa", outgoingPressure, ...
    "incoming_pressure_pa", incomingPressure, ...
    "boundary_pressure_pa", boundaryPressure, ...
    "boundary_density_kg_m3", boundaryDensity, ...
    "boundary_velocity_mps", boundaryVelocity, ...
    "gamma", gamma, ...
    "state_order", numel(state), ...
    "boundary_type", "radiation_impedance_state_space");
end

function validatePackage(package, state)
required = ["state_space_A", "state_space_B", "state_space_C", "state_space_D"];
if ~all(isfield(package, required)) || numel(state) ~= 2 || ...
        any(~isfinite(state)) || ~isequal(size(package.state_space_A), [2, 2]) || ...
        ~isequal(size(package.state_space_B), [2, 1]) || ...
        ~isequal(size(package.state_space_C), [1, 2]) || ...
        ~isequal(size(package.state_space_D), [1, 1]) || ...
        any(~isfinite(package.state_space_A), "all") || ...
        any(~isfinite(package.state_space_B), "all") || ...
        any(~isfinite(package.state_space_C), "all") || ...
        ~isfinite(package.state_space_D)
    error("S12:Radiation:InvalidState", ...
        "Radiation package and stage state must be finite 2-state data.");
end
end

function validateAmbient(ambient)
required = ["pressure_pa", "density_kg_m3", "sound_speed_mps"];
if ~all(isfield(ambient, required)) || ambient.pressure_pa <= 0 || ...
        ambient.density_kg_m3 <= 0 || ambient.sound_speed_mps <= 0 || ...
        any(~isfinite([ambient.pressure_pa, ambient.density_kg_m3, ...
        ambient.sound_speed_mps]))
    error("S12:Radiation:InvalidState", ...
        "Ambient radiation state must have positive finite primitives.");
end
end
