function tests = test_s12_muscl_qualification_report
%TEST_S12_MUSCL_QUALIFICATION_REPORT Verify deterministic qualification reports.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
s12Root = fileparts(fileparts(mfilename("fullpath")));
benchmarkRoot = fullfile(s12Root, "benchmark");
addpath(benchmarkRoot);
testCase.addTeardown(@() rmpath(benchmarkRoot));
end

function testReportOnlyPreservesQualificationAcceptance(testCase)
runDirectory = tempname;
reportDirectory = tempname;
mkdir(runDirectory);
testCase.addTeardown(@() removeDirectory(runDirectory));
testCase.addTeardown(@() removeDirectory(reportDirectory));

written = s12_write_sprint2_qualification_artifacts( ...
    sampleResult("failed"), runDirectory);
manifest = fullfile(runDirectory, "benchmark-result.json");
rebuilt = run_s12_muscl_final_qualification("report-only", ...
    SourceManifest=manifest, OutputDirectory=reportDirectory);

expected = ["benchmark-report.md", "benchmark-result.json", ...
    "sprint2-case-comparison.csv", "sprint2-smooth-spatial.csv", ...
    "sprint2-smooth-spatial-convergence.png"];
for index = 1:numel(expected)
    verifyEqual(testCase, readBytes(fullfile(runDirectory, expected(index))), ...
        readBytes(fullfile(reportDirectory, expected(index))));
end
verifyEqual(testCase, written.acceptance.status, "failed");
verifyEqual(testCase, rebuilt.acceptance.status, "failed");
end

function result = sampleResult(status)
first = spatialMetrics([1e-2, 5e-3], 1.0);
muscl = spatialMetrics([2e-3, 5e-4], 2.0);
result = struct( ...
    "schema", "benchmark.schema.v1", ...
    "schema_minor", 1, ...
    "suite", struct("profile", "test", ...
        "selector", "sprint2_muscl_final_qualification"), ...
    "environment", struct("git_commit", "deadbeef", ...
        "matlab_release", "R2026a"), ...
    "source_results", struct("first_order_acceptance", "passed", ...
        "muscl_minmod_acceptance", "passed"), ...
    "cases", struct("id", "smooth_periodic_entropy_wave_spatial", ...
        "category", "spatial_accuracy", "first_order", first, ...
        "muscl_minmod", muscl, "rho_error_ratio", ...
        muscl.rho_l1_error ./ first.rho_l1_error), ...
    "artifacts", struct([]), ...
    "acceptance", struct("status", status, ...
        "checks", struct("id", "manual_sentinel", "passed", false)));
end

function metrics = spatialMetrics(rhoError, order)
metrics = struct( ...
    "cell_counts", [50, 100], ...
    "rho_l1_error", rhoError, ...
    "velocity_l1_error", [0, 0], ...
    "pressure_l1_error", [0, 0], ...
    "rho_observed_order", order, ...
    "velocity_observed_order", NaN, ...
    "pressure_observed_order", NaN, ...
    "dt_requested", [1e-3, 5e-4], ...
    "dt_effective", [1e-3, 5e-4], ...
    "cfl_clipped", [false, false], ...
    "end_time_clipped", [false, false], ...
    "uses_cell_averages", true);
end

function bytes = readBytes(path)
fileId = fopen(path, "rb");
cleanup = onCleanup(@() fclose(fileId));
bytes = fread(fileId, Inf, "*uint8");
end

function removeDirectory(path)
if isfolder(path)
    rmdir(path, "s");
end
end
