function definition = s12_fanno_fvm_case_definition(profile)
%S12_FANNO_FVM_CASE_DEFINITION Freeze the Sprint 4B balance-law identifiers.
arguments
    profile (1,1) string {mustBeMember(profile, ["quick", "full"])}
end
definition = struct( ...
    "profile", profile, ...
    "spatial_scheme", "muscl_minmod_pp", ...
    "balance_law_mode", "fanno_constant_darcy", ...
    "friction_source_id", "darcy_wall_exact.v1", ...
    "friction_factor_convention", "darcy", ...
    "source_integrator_id", "strang_exact_friction_ssprk3.v1", ...
    "source_split_order", "source_half_hyperbolic_ssprk3_source_half", ...
    "boundary_id", "subsonic_fanno_validation.v1", ...
    "initialization_id", "analytical_fanno_cell_average.v1", ...
    "cell_average_reference_id", "gauss_legendre_conservative.v1", ...
    "grid_cell_counts", [50, 100, 200, 400]);
end
