function [stateNext, diagnostics] = s12_fanno_exact_friction_step( ...
        state, gamma, darcyFrictionFactor, hydraulicDiameter, dt)
%S12_FANNO_EXACT_FRICTION_STEP Apply the exact stationary-wall Darcy source.
validateInputs(state, gamma, darcyFrictionFactor, hydraulicDiameter, dt);
[density, velocity, pressure] = primitive(state, gamma);
k = darcyFrictionFactor / (2 * hydraulicDiameter);
nextVelocity = velocity ./ (1 + k * abs(velocity) * dt);
stateNext = state;
stateNext(2, :) = density .* nextVelocity;
[~, ~, nextPressure] = primitive(stateNext, gamma);
if any(~isfinite(stateNext), "all") || any(nextPressure <= 0)
    error("S12:Fanno:InvalidState", ...
        "Exact Darcy friction produced a nonphysical state.");
end
tolerance = 128 * eps(max([1, abs(pressure), abs(nextPressure)], [], "all"));
if any(nextPressure < pressure - tolerance)
    error("S12:Fanno:PressureDecrease", ...
        "An adiabatic stationary-wall friction step cannot reduce pressure.");
end
diagnostics = struct( ...
    "friction_convention", "darcy", ...
    "darcy_friction_factor", darcyFrictionFactor, ...
    "source_coefficient", k, ...
    "source_applied", logical(k > 0 && dt > 0 && any(velocity ~= 0)), ...
    "velocity_sign_preserved", all(sign(nextVelocity) == sign(velocity)), ...
    "velocity_magnitude_nonincreasing", all(abs(nextVelocity) <= abs(velocity)), ...
    "density_change_max", max(abs(stateNext(1, :) - state(1, :))), ...
    "total_energy_change_max", max(abs(stateNext(3, :) - state(3, :))), ...
    "minimum_pressure", min(nextPressure), ...
    "momentum_source_integral", sum(stateNext(2, :) - state(2, :)));
end

function validateInputs(state, gamma, fDarcy, diameter, dt)
if ~isa(state, "double") || size(state, 1) ~= 3 || isempty(state) || ...
        any(~isfinite(state), "all") || ~isscalar(gamma) || ...
        ~isfinite(gamma) || gamma <= 1 || ~isscalar(fDarcy) || ...
        ~isfinite(fDarcy) || fDarcy < 0 || ~isscalar(diameter) || ...
        ~isfinite(diameter) || diameter <= 0 || ~isscalar(dt) || ...
        ~isfinite(dt) || dt < 0
    error("S12:Fanno:InvalidInput", "Invalid exact Darcy friction input.");
end
[density, ~, pressure] = primitive(state, gamma);
if any(density <= 0) || any(pressure <= 0)
    error("S12:Fanno:InvalidInput", "Friction input state must be physical.");
end
end

function [density, velocity, pressure] = primitive(state, gamma)
density = state(1, :);
velocity = state(2, :) ./ density;
pressure = (gamma - 1) * (state(3, :) - 0.5 * density .* velocity.^2);
end
