function definition = s12_fanno_case_definition(profile)
%S12_FANNO_CASE_DEFINITION Define the matched analytical/Pipe(G) case.
arguments
    profile (1, 1) string {mustBeMember(profile, ["quick", "full"])}
end

definition = struct( ...
    "id", "fanno_pipe_g_cross_validation", ...
    "profile", profile, ...
    "gas_constant", 287, ...
    "cp", 1000, ...
    "dynamic_viscosity", 18e-6, ...
    "diameter", 0.1, ...
    "roughness", 15e-6, ...
    "inlet_static_pressure", 2e5, ...
    "inlet_static_temperature", 300, ...
    "mass_flow", 1, ...
    "additional_equivalent_length", 0, ...
    "wall_boundary", "perfect_insulator", ...
    "inlet_boundary", "fixed_static_p_T", ...
    "outlet_boundary", "fixed_mass_flow", ...
    "friction_convention", "darcy_f_D_L_over_D", ...
    "segment_counts", [1, 5], ...
    "stop_time", 100, ...
    "steady_window_fraction", 0.1, ...
    "steady_relative_span_tolerance", 1e-6);
definition.area = pi * definition.diameter^2 / 4;
definition.gamma = definition.cp / ...
    (definition.cp - definition.gas_constant);

if profile == "quick"
    definition.lengths = 1;
    definition.single_error_limit = 5e-4;
    definition.segmented_error_limit = 5e-4;
else
    definition.lengths = [1, 76, 156];
    definition.single_error_limit = 0.02;
    definition.segmented_error_limit = 0.002;
end
end
