function result = s12_run_fanno_pipe_g(definition)
%S12_RUN_FANNO_PIPE_G Compare analytical Fanno flow with Pipe (G).
arguments
    definition (1, 1) struct
end

root = fileparts(fileparts(fileparts(mfilename("fullpath"))));
modelRoot = fullfile(root, "models", "pipe_ref");
singleModel = fullfile(modelRoot, "s12_fanno_pipe_g_ref.slx");
segmentedModel = fullfile(modelRoot, "s12_fanno_pipe_g_segmented_ref.slx");
if ~isfile(singleModel) || ~isfile(segmentedModel)
    error("S12:Fanno:MissingModel", "Controlled Pipe (G) models are missing.");
end

reynolds = definition.mass_flow * definition.diameter / ...
    (definition.dynamic_viscosity * definition.area);
darcyFactor = 1 / (-1.8 * log10(6.9 / reynolds + ...
    (definition.roughness / (3.7 * definition.diameter))^1.11))^2;
inletDensity = definition.inlet_static_pressure / ...
    (definition.gas_constant * definition.inlet_static_temperature);
inletSoundSpeed = sqrt(definition.gamma * definition.gas_constant * ...
    definition.inlet_static_temperature);
inletMach = definition.mass_flow / ...
    (inletDensity * inletSoundSpeed * definition.area);

analyticalCell = cell(1, numel(definition.lengths));
for index = 1:numel(definition.lengths)
    analyticalCell{index} = s12_fanno_reference(struct( ...
        "static_pressure", definition.inlet_static_pressure, ...
        "static_temperature", definition.inlet_static_temperature, ...
        "mach", inletMach, ...
        "gamma", definition.gamma, ...
        "gas_constant", definition.gas_constant, ...
        "area", definition.area, ...
        "diameter", definition.diameter, ...
        "length", definition.lengths(index), ...
        "darcy_friction_factor", darcyFactor));
end
analytical = [analyticalCell{:}];

single = runModel(singleModel, definition, analytical);
segmented = runModel(segmentedModel, definition, analytical);
chokeMargin = zeros(size(definition.lengths));
for index = 1:numel(analytical)
    chokeMargin(index) = analytical(index).remaining_length_to_choke / ...
        (analytical(index).remaining_length_to_choke + definition.lengths(index));
end

passed = single.all_finite && segmented.all_finite && ...
    single.steady && segmented.steady && ...
    single.maximum_relative_error < definition.single_error_limit && ...
    segmented.maximum_relative_error < definition.segmented_error_limit;
result = struct( ...
    "status", "failed", ...
    "case_definition", definition, ...
    "physical_assumptions", ...
        "steady_1d_constant_area_adiabatic_calorically_perfect_subsonic", ...
    "friction_convention", definition.friction_convention, ...
    "reynolds_number", reynolds, ...
    "darcy_friction_factor", darcyFactor, ...
    "inlet_mach", inletMach, ...
    "analytical", analytical, ...
    "single", single, ...
    "segmented", segmented, ...
    "minimum_choke_margin", min(chokeMargin), ...
    "retry_count", 0);
if passed
    result.status = "passed";
else
    result.status = "failed";
end
end

function summary = runModel(modelPath, definition, analytical)
[~, modelName] = fileparts(modelPath);
load_system(modelPath);
cleanup = onCleanup(@() closeIfLoaded(modelName));

mach = zeros(size(definition.lengths));
pressure = zeros(size(definition.lengths));
temperature = zeros(size(definition.lengths));
steadySpan = zeros(numel(definition.lengths), 3);
stationCount = 5 * double(modelName == "s12_fanno_pipe_g_segmented_ref");
stationFractions = (1:stationCount) / 5;
stationMach = zeros(numel(definition.lengths), stationCount);
stationPressure = zeros(numel(definition.lengths), stationCount);
stationTemperature = zeros(numel(definition.lengths), stationCount);
for index = 1:numel(definition.lengths)
    input = Simulink.SimulationInput(modelName);
    input = setVariables(input, definition, definition.lengths(index));
    input = input.setModelParameter("StopTime", string(definition.stop_time), ...
        "ReturnWorkspaceOutputs", "on");
    output = sim(input);
    logNode = output.get(string(get_param(modelName, "SimscapeLogName")));
    if ~isempty(stationFractions)
        for stationIndex = 1:numel(stationFractions)
            pipeNode = logNode.("Pipe_" + stationIndex);
            stationMach(index, stationIndex) = ...
                finalSeriesValue(pipeNode.Mach_B.series, "1");
            stationPressure(index, stationIndex) = ...
                finalSeriesValue(pipeNode.B.p.series, "Pa");
            stationTemperature(index, stationIndex) = ...
                finalSeriesValue(pipeNode.B.T.series, "K");
        end
    end
    machSeries = logNode.Mach_Number_Sensor_G.Mach.series;
    pressureSeries = logNode.Pressure_Temperature_Sensor_G.Pa.series;
    temperatureSeries = logNode.Pressure_Temperature_Sensor_G.T.series;
    machValues = double(machSeries.values("1"));
    pressureValues = double(pressureSeries.values("Pa"));
    temperatureValues = double(temperatureSeries.values("K"));
    mach(index) = machValues(end);
    pressure(index) = pressureValues(end);
    temperature(index) = temperatureValues(end);
    steadySpan(index, :) = [ ...
        tailSpan(machSeries.time, machValues, definition), ...
        tailSpan(pressureSeries.time, pressureValues, definition), ...
        tailSpan(temperatureSeries.time, temperatureValues, definition)];
end

referenceMach = arrayfun(@(item) item.outlet.mach, analytical);
referencePressure = arrayfun(@(item) item.outlet.static_pressure, analytical);
referenceTemperature = arrayfun(@(item) item.outlet.static_temperature, analytical);
relativeError = [ ...
    abs(mach - referenceMach) ./ referenceMach; ...
    abs(pressure - referencePressure) ./ referencePressure; ...
    abs(temperature - referenceTemperature) ./ referenceTemperature];
summary = struct( ...
    "model", modelName, ...
    "lengths", definition.lengths, ...
    "mach", mach, ...
    "static_pressure", pressure, ...
    "static_temperature", temperature, ...
    "relative_error", relativeError, ...
    "maximum_relative_error", max(relativeError, [], "all"), ...
    "steady_relative_span", steadySpan, ...
    "station_positions_fraction", stationFractions, ...
    "station_mach", stationMach, ...
    "station_static_pressure", stationPressure, ...
    "station_static_temperature", stationTemperature, ...
    "steady", all(steadySpan < ...
        definition.steady_relative_span_tolerance, "all"), ...
    "all_finite", all(isfinite([mach, pressure, temperature]), "all"));
clear cleanup
end

function value = finalSeriesValue(series, unit)
values = double(series.values(unit));
value = values(end);
end

function input = setVariables(input, definition, lengthValue)
values = struct( ...
    "s12_fanno_D", definition.diameter, ...
    "s12_fanno_A", definition.area, ...
    "s12_fanno_roughness", definition.roughness, ...
    "s12_fanno_R", definition.gas_constant, ...
    "s12_fanno_cp", definition.cp, ...
    "s12_fanno_mu", definition.dynamic_viscosity, ...
    "s12_fanno_p1", definition.inlet_static_pressure, ...
    "s12_fanno_T1", definition.inlet_static_temperature, ...
    "s12_fanno_mdot", definition.mass_flow, ...
    "s12_fanno_L", lengthValue);
names = fieldnames(values);
for index = 1:numel(names)
    input = input.setVariable(names{index}, values.(names{index}));
end
end

function value = tailSpan(time, data, definition)
startTime = time(end) * (1 - definition.steady_window_fraction);
tail = data(time >= startTime);
value = (max(tail) - min(tail)) / max(max(abs(tail)), realmin);
end

function closeIfLoaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
