function result = s12_run_fanno_fvm(config)
%S12_RUN_FANNO_FVM Run Strang-coupled exact friction with frozen PP FVM.
validateConfig(config);
boundary = string(config.boundary);
if boundary ~= "periodic_uniform_friction" && boundary ~= "subsonic_fanno_validation.v1"
    error("S12:Fanno:UnsupportedBoundary", ...
        "The Fanno adapter has not yet enabled this validation boundary.");
end
state = config.initial_state;
cellCount = size(state, 2);
dx = config.length_m / cellCount;
modelName = "s12_euler_fvm_fanno_ref";
modelRoot = fullfile(fileparts(fileparts(fileparts(mfilename("fullpath")))), ...
    "models", "fvm_ref");
modelPath = fullfile(modelRoot, modelName + ".slx");
if ~isfile(modelPath)
    error("S12:Fanno:MissingModel", "Controlled Fanno source model is missing.");
end
wasLoaded = bdIsLoaded(modelName);
load_system(modelPath);
cleanup = onCleanup(@() closeIfOwned(modelName, wasLoaded));
hyperbolicCleanup = keepHyperbolicModelsLoaded(boundary, modelRoot); %#ok<NASGU>
time = 0;
stepCount = 0;
maximumCfl = 0;
sourceDiagnostics = emptySourceDiagnostics();
hyperbolicHistory = cell(1, config.max_steps);
normalizedStateResidual = NaN;
steadyMode = isfield(config, "steady_criteria");
steadyStateReached = false;
steadyWindowCount = 0;
endTimeClippingCount = 0;
terminationReason = "maximum_physical_time";
while time < config.end_time_s
    if stepCount >= config.max_steps
        if steadyMode
            terminationReason = "maximum_steps";
            break
        end
        error("S12:Fanno:MaximumSteps", "Fanno adapter exceeded max_steps.");
    end
    fullDt = requestedStepDt(state, config, dx, boundary, Inf);
    if steadyMode
        if time + fullDt > config.end_time_s
            break
        end
        dt = fullDt;
    else
        dt = min(fullDt, config.end_time_s - time);
        if dt < fullDt - 32 * eps(max(1, fullDt))
            endTimeClippingCount = endTimeClippingCount + 1;
        end
    end
    baseState = state;
    [sourceHalf, firstSource] = sourceStep(modelName, baseState, config, dt / 2);
    hyperbolic = hyperbolicStep(sourceHalf, config, dx, dt, boundary);
    if any(abs(hyperbolic.stage_dt - dt) > 32 * eps(max(1, dt)))
        error("S12:Fanno:CflClipped", ...
            "Frozen PP hyperbolic stages changed the Strang step dt.");
    end
    [state, secondSource] = sourceStep(modelName, hyperbolic.final_state, config, dt / 2);
    validateState(state, config.gamma);
    normalizedStateResidual = normalizedStateChange(state, baseState);
    sourceDiagnostics = accumulateSource(sourceDiagnostics, firstSource, secondSource);
    hyperbolicHistory{stepCount + 1} = hyperbolic.qualification;
    maximumCfl = max(maximumCfl, ...
        dt * waveSpeedWithBoundary(sourceHalf, config, boundary) / dx);
    time = time + dt;
    stepCount = stepCount + 1;
    if steadyMode
        current = stateBalanceMetrics(state, config, dx, normalizedStateResidual);
        if meetsSteadyCriteria(current.values, config.steady_criteria)
            steadyWindowCount = steadyWindowCount + 1;
        else
            steadyWindowCount = 0;
        end
        if steadyWindowCount >= config.steady_criteria.required_windows
            steadyStateReached = true;
            terminationReason = "steady_state";
            break
        end
    end
end
if stepCount == 0
    error("S12:Fanno:NoCompletedStep", ...
        "No complete Strang step fit inside the configured physical time.");
end
balanceMetrics = stateBalanceMetrics(state, config, dx, normalizedStateResidual);
ppDiagnostics = aggregateHyperbolicDiagnostics(hyperbolicHistory(1:stepCount));
qualification = struct( ...
    "spatial_scheme", "muscl_minmod_pp", ...
    "balance_law_mode", "fanno_constant_darcy", ...
    "friction_source_id", "darcy_wall_exact.v1", ...
    "source_integrator_id", "strang_exact_friction_ssprk3.v1", ...
    "source_split_order", "strang_second_order", ...
    "source_split_sequence", "source_half_hyperbolic_ssprk3_source_half", ...
    "friction_convention", "darcy", ...
    "boundary_id", string(config.boundary), ...
    "cfl_safety_factor", cflSafetyFactor(config), ...
    "clipping_count", 0, ...
    "flux_fallback_count", 0, ...
    "retry_count", 0, ...
    "rejected_step_count", 0, ...
    "end_time_clipping_count", endTimeClippingCount, ...
    "minimum_density", min(state(1, :)), ...
    "minimum_pressure", minimumPressure(state, config.gamma), ...
    "source_step_count", sourceDiagnostics.step_count, ...
    "source_density_change_max", sourceDiagnostics.density_change_max, ...
    "source_energy_change_max", sourceDiagnostics.energy_change_max, ...
    "sonic_margin", balanceMetrics.sonic_margin);
qualification = addPpDiagnostics(qualification, ppDiagnostics);
result = struct( ...
    "final_state", state, ...
    "final_time_s", time, ...
    "step_count", stepCount, ...
    "maximum_cfl", maximumCfl, ...
    "conservation_residual", sum(state - config.initial_state, 2).', ...
    "spatial_scheme", "muscl_minmod_pp", ...
    "balance_law_mode", "fanno_constant_darcy", ...
    "friction_source_id", "darcy_wall_exact.v1", ...
    "source_integrator_id", "strang_exact_friction_ssprk3.v1", ...
    "boundary_id", boundary, ...
    "cfl_safety_factor", cflSafetyFactor(config), ...
    "model_path", modelPath, ...
    "balance_metrics", balanceMetrics.values, ...
    "balance_metric_id", balanceMetrics.id, ...
    "balance_boundary_trim_cells_per_side", balanceMetrics.trim_cells_per_side, ...
    "sonic_margin", balanceMetrics.sonic_margin, ...
    "outlet", balanceMetrics.outlet, ...
    "steady_state_reached", steadyStateReached, ...
    "steady_state_time_s", time, ...
    "steady_window_count", steadyWindowCount, ...
    "termination_reason", terminationReason, ...
    "qualification", qualification);
end

function validateConfig(config)
required = ["gamma", "gas_constant", "length_m", "hydraulic_diameter_m", ...
    "darcy_friction_factor", "cfl", "end_time_s", "max_steps", ...
    "boundary", "initial_state"];
if ~isstruct(config) || ~all(isfield(config, required)) || ...
        ~isequal(size(config.initial_state, 1), 3) || isempty(config.initial_state) || ...
        any(~isfinite(config.initial_state), "all") || ~isscalar(config.gamma) || ...
        config.gamma <= 1 || ~isscalar(config.length_m) || config.length_m <= 0 || ...
        ~isscalar(config.hydraulic_diameter_m) || config.hydraulic_diameter_m <= 0 || ...
        ~isscalar(config.darcy_friction_factor) || config.darcy_friction_factor < 0 || ...
        ~isscalar(config.cfl) || config.cfl <= 0 || config.cfl > 0.5 || ...
        ~isscalar(config.end_time_s) || config.end_time_s < 0 || ...
        ~isscalar(config.max_steps) || config.max_steps < 1 || ...
        config.max_steps ~= floor(config.max_steps)
    error("S12:Fanno:InvalidInput", "Invalid Fanno FVM adapter configuration.");
end
validateState(config.initial_state, config.gamma);
boundary = string(config.boundary);
if boundary == "subsonic_fanno_validation.v1"
    requiredBoundary = ["inlet_static_pressure", "inlet_static_temperature", ...
        "outlet_mass_flux"];
    if ~all(isfield(config, requiredBoundary)) || ...
            ~isscalar(config.inlet_static_pressure) || ...
            ~isscalar(config.inlet_static_temperature) || ...
            ~isscalar(config.outlet_mass_flux) || ...
            config.inlet_static_pressure <= 0 || ...
            config.inlet_static_temperature <= 0 || config.outlet_mass_flux <= 0
        error("S12:Fanno:InvalidInput", ...
            "Invalid validation-only Fanno boundary configuration.");
    end
end
if isfield(config, "steady_criteria")
    validateSteadyCriteria(config.steady_criteria);
end
end

function result = hyperbolicStep(state, config, dx, dt, boundary)
if boundary == "periodic_uniform_friction"
    periodic = s12_run_periodic_ssprk3(state, config.gamma, dx, dt, 1, ...
        config.cfl, Reconstruction="muscl_minmod_pp");
    result = struct("final_state", periodic.final_state, ...
        "stage_dt", periodic.used_dt, ...
        "qualification", periodic.qualification);
    return
end
result = s12_fanno_pp_characteristic_step(state, config.gamma, dx, dt, ...
    GasConstant=config.gas_constant, ...
    InletStaticPressure=config.inlet_static_pressure, ...
    InletStaticTemperature=config.inlet_static_temperature, ...
    OutletMassFlux=config.outlet_mass_flux, Cfl=config.cfl);
result.qualification = characteristicQualification(result, config.gamma);
end

function dt = requestedStepDt(state, config, dx, boundary, remainingTime)
alpha = waveSpeedWithBoundary(state, config, boundary);
dt = min(cflSafetyFactor(config) * config.cfl * dx / alpha, remainingTime);
if boundary == "periodic_uniform_friction"
    return
end
for iteration = 1:3
    forecast = s12_fanno_exact_friction_step(state, config.gamma, ...
        config.darcy_friction_factor, config.hydraulic_diameter_m, dt / 2);
    alpha = waveSpeedWithBoundary(forecast, config, boundary);
    dt = min(cflSafetyFactor(config) * config.cfl * dx / alpha, remainingTime);
end
end

function factor = cflSafetyFactor(config)
factor = 0.9;
if isfield(config, "cfl_safety_factor")
    factor = config.cfl_safety_factor;
end
if ~isscalar(factor) || ~isfinite(factor) || factor <= 0 || factor > 1
    error("S12:Fanno:InvalidInput", "Invalid fixed Fanno CFL safety factor.");
end
end

function validateSteadyCriteria(criteria)
required = ["state_residual_limit", "mass_flow_uniformity_limit", ...
    "mass_balance_limit", "energy_balance_limit", ...
    "momentum_balance_limit", "stagnation_temperature_spread_limit", ...
    "required_windows"];
if ~isstruct(criteria) || ~all(isfield(criteria, required))
    error("S12:Fanno:InvalidInput", "Incomplete Fanno steady-state criteria.");
end
limits = [criteria.state_residual_limit, ...
    criteria.mass_flow_uniformity_limit, criteria.mass_balance_limit, ...
    criteria.energy_balance_limit, criteria.momentum_balance_limit, ...
    criteria.stagnation_temperature_spread_limit];
if any(~isfinite(limits)) || any(limits < 0) || ...
        ~isscalar(criteria.required_windows) || criteria.required_windows < 1 || ...
        criteria.required_windows ~= floor(criteria.required_windows)
    error("S12:Fanno:InvalidInput", "Invalid Fanno steady-state criteria.");
end
end

function passed = meetsSteadyCriteria(metrics, criteria)
passed = metrics.normalized_state_residual <= criteria.state_residual_limit && ...
    metrics.mass_flow_uniformity <= criteria.mass_flow_uniformity_limit && ...
    metrics.mass_balance_residual <= criteria.mass_balance_limit && ...
    metrics.energy_balance_residual <= criteria.energy_balance_limit && ...
    metrics.source_balanced_momentum_residual <= criteria.momentum_balance_limit && ...
    metrics.stagnation_temperature_spread <= ...
        criteria.stagnation_temperature_spread_limit;
end

function alpha = waveSpeedWithBoundary(state, config, boundary)
if boundary == "periodic_uniform_friction"
    alpha = waveSpeed(state, config.gamma);
    return
end
left = s12_fanno_inlet_pt_boundary(state(:, 1), config.gamma, ...
    config.gas_constant, config.inlet_static_pressure, ...
    config.inlet_static_temperature);
right = s12_fanno_outlet_mdot_boundary(state(:, end), config.gamma, ...
    config.outlet_mass_flux);
alpha = waveSpeed([left, left, state, right, right], config.gamma);
end

function [stateNext, diagnostics] = sourceStep(modelName, state, config, dt)
workspace = get_param(modelName, "ModelWorkspace");
setValue(workspace, "S12_Fanno_State", state);
setValue(workspace, "S12_Fanno_Gamma", config.gamma);
setValue(workspace, "S12_Fanno_DarcyFactor", config.darcy_friction_factor);
setValue(workspace, "S12_Fanno_HydraulicDiameter", config.hydraulic_diameter_m);
setValue(workspace, "S12_Fanno_Dt", dt);
output = sim(modelName);
values = output.S12_FannoStateNext;
stateNext = values(:, :, end);
[~, diagnostics] = s12_fanno_exact_friction_step( ...
    state, config.gamma, config.darcy_friction_factor, ...
    config.hydraulic_diameter_m, dt);
end

function setValue(workspace, name, value)
parameter = workspace.getVariable(name);
if isa(parameter, "Simulink.Parameter")
    parameter.Value = value;
    workspace.assignin(name, parameter);
else
    workspace.assignin(name, value);
end
end

function alpha = waveSpeed(state, gamma)
density = state(1, :);
velocity = state(2, :) ./ density;
pressure = (gamma - 1) * (state(3, :) - 0.5 * density .* velocity.^2);
alpha = max(abs(velocity) + sqrt(gamma * pressure ./ density));
end

function metrics = stateBalanceMetrics(state, config, dx, stateResidual)
density = state(1, :);
velocity = state(2, :) ./ density;
pressure = (config.gamma - 1) * (state(3, :) - ...
    0.5 * density .* velocity.^2);
temperature = pressure ./ (density * config.gas_constant);
soundSpeed = sqrt(config.gamma * pressure ./ density);
mach = velocity ./ soundSpeed;
massFlux = density .* velocity;
totalEnthalpy = (state(3, :) + pressure) ./ density;
stagnationTemperature = temperature .* (1 + ...
    0.5 * (config.gamma - 1) * mach.^2);
coefficient = config.darcy_friction_factor / (2 * config.hydraulic_diameter_m);
wallMomentumSource = sum(-coefficient * density .* velocity .* abs(velocity)) * dx;
metricMassFlux = massFlux;
metricEnthalpy = totalEnthalpy;
metricStagnationTemperature = stagnationTemperature;
momentumFluxIn = density(1) * velocity(1)^2 + pressure(1);
momentumFluxOut = density(end) * velocity(end)^2 + pressure(end);
outletState = state(:, end);
metricId = "cell_center_full_domain.v1";
trimCells = 0;
if string(config.boundary) == "subsonic_fanno_validation.v1"
    trimCells = 2;
    if numel(density) <= 2 * trimCells
        error("S12:Fanno:InvalidInput", ...
            "Fanno boundary-aware balance metrics require more physical cells.");
    end
    leftBoundary = s12_fanno_inlet_pt_boundary(state(:, 1), config.gamma, ...
        config.gas_constant, config.inlet_static_pressure, ...
        config.inlet_static_temperature);
    rightBoundary = s12_fanno_outlet_mdot_boundary(state(:, end), ...
        config.gamma, config.outlet_mass_flux);
    interior = (1 + trimCells):(numel(density) - trimCells);
    metricMassFlux = [leftBoundary(2), massFlux(interior), rightBoundary(2)];
    metricEnthalpy = totalEnthalpy(interior);
    metricStagnationTemperature = stagnationTemperature(interior);
    [leftDensity, leftVelocity, leftPressure] = ...
        primitiveState(leftBoundary, config.gamma);
    [rightDensity, rightVelocity, rightPressure] = ...
        primitiveState(rightBoundary, config.gamma);
    momentumFluxIn = leftDensity * leftVelocity^2 + leftPressure;
    momentumFluxOut = rightDensity * rightVelocity^2 + rightPressure;
    outletState = rightBoundary;
    metricId = "fanno_boundary_flux_interior_trim2.v1";
end
balance = s12_fanno_balance_metrics(struct( ...
    "mass_flux", metricMassFlux, ...
    "total_enthalpy", metricEnthalpy, ...
    "stagnation_temperature", metricStagnationTemperature, ...
    "momentum_flux_in", momentumFluxIn, ...
    "momentum_flux_out", momentumFluxOut, ...
    "wall_momentum_source_integral", wallMomentumSource, ...
    "state_change_residual", stateResidual));
metrics = struct("values", balance, "id", metricId, ...
    "trim_cells_per_side", trimCells, ...
    "sonic_margin", 1 - max(mach), ...
    "outlet", outletPrimitive(outletState, config));
end

function outlet = outletPrimitive(state, config)
[density, velocity, pressure] = primitiveState(state, config.gamma);
temperature = pressure / (density * config.gas_constant);
mach = velocity / sqrt(config.gamma * config.gas_constant * temperature);
outlet = struct("density", density, "velocity", velocity, ...
    "pressure", pressure, "temperature", temperature, ...
    "mach", mach, "mass_flux", density * velocity);
end

function [density, velocity, pressure] = primitiveState(state, gamma)
density = state(1);
velocity = state(2) / density;
pressure = (gamma - 1) * (state(3) - 0.5 * density * velocity^2);
end

function value = normalizedStateChange(current, previous)
scale = max(abs(previous), 1);
value = max(abs(current - previous) ./ scale, [], "all");
end

function minimum = minimumPressure(state, gamma)
density = state(1, :);
velocity = state(2, :) ./ density;
minimum = min((gamma - 1) * (state(3, :) - 0.5 * density .* velocity.^2));
end

function validateState(state, gamma)
if any(~isfinite(state), "all") || any(state(1, :) <= 0) || ...
        minimumPressure(state, gamma) <= 0
    error("S12:Fanno:InvalidState", "Fanno adapter encountered a nonphysical state.");
end
end

function diagnostics = emptySourceDiagnostics()
diagnostics = struct("step_count", 0, "density_change_max", 0, ...
    "energy_change_max", 0);
end

function accumulated = accumulateSource(accumulated, first, second)
for diagnostics = [first, second]
    accumulated.step_count = accumulated.step_count + 1;
    accumulated.density_change_max = max(accumulated.density_change_max, ...
        diagnostics.density_change_max);
    accumulated.energy_change_max = max(accumulated.energy_change_max, ...
        diagnostics.total_energy_change_max);
end
end

function qualification = characteristicQualification(result, gamma)
diagnostics = result.stage_diagnostics;
cellDensity = zeros(1, 3);
cellPressure = zeros(1, 3);
for stageIndex = 1:3
    state = result.stage_states{stageIndex};
    cellDensity(stageIndex) = min(state(1, :));
    cellPressure(stageIndex) = minimumPressure(state, gamma);
end
qualification = struct( ...
    "rho_floor", result.rho_floor, "p_floor", result.p_floor, ...
    "reconstruction_pp_activation_count", sum(diagnostics(4, :)), ...
    "flux_pp_activation_count", sum(diagnostics(10, :)), ...
    "reconstruction_pp_min_theta", min(diagnostics(6, :)), ...
    "flux_pp_min_theta", min(diagnostics(13, :)), ...
    "minimum_reconstructed_density", min(diagnostics(7, :)), ...
    "minimum_reconstructed_pressure", min(diagnostics(8, :)), ...
    "invalid_reconstruction_count", sum(diagnostics(9, :)), ...
    "minimum_anchor_partial_density", min(diagnostics(14, :)), ...
    "minimum_anchor_partial_pressure", min(diagnostics(15, :)), ...
    "minimum_final_partial_density", min(diagnostics(16, :)), ...
    "minimum_final_partial_pressure", min(diagnostics(17, :)), ...
    "maximum_flux_correction_norm", max(diagnostics(19, :)), ...
    "invalid_stage_count", sum(diagnostics(20, :)), ...
    "minimum_cell_density_by_stage", cellDensity, ...
    "minimum_cell_pressure_by_stage", cellPressure, ...
    "minimum_interface_density_by_stage", diagnostics(7, :), ...
    "minimum_interface_pressure_by_stage", diagnostics(8, :), ...
    "minimum_anchor_partial_density_by_stage", diagnostics(14, :), ...
    "minimum_anchor_partial_pressure_by_stage", diagnostics(15, :), ...
    "minimum_final_partial_density_by_stage", diagnostics(16, :), ...
    "minimum_final_partial_pressure_by_stage", diagnostics(17, :));
end

function summary = aggregateHyperbolicDiagnostics(history)
summary = history{1};
sumFields = ["reconstruction_pp_activation_count", ...
    "flux_pp_activation_count", "invalid_reconstruction_count", ...
    "invalid_stage_count"];
minimumFields = ["rho_floor", "p_floor", ...
    "reconstruction_pp_min_theta", "flux_pp_min_theta", ...
    "minimum_reconstructed_density", "minimum_reconstructed_pressure", ...
    "minimum_anchor_partial_density", "minimum_anchor_partial_pressure", ...
    "minimum_final_partial_density", "minimum_final_partial_pressure", ...
    "minimum_cell_density_by_stage", "minimum_cell_pressure_by_stage", ...
    "minimum_interface_density_by_stage", ...
    "minimum_interface_pressure_by_stage", ...
    "minimum_anchor_partial_density_by_stage", ...
    "minimum_anchor_partial_pressure_by_stage", ...
    "minimum_final_partial_density_by_stage", ...
    "minimum_final_partial_pressure_by_stage"];
for historyIndex = 2:numel(history)
    current = history{historyIndex};
    for field = sumFields
        summary.(field) = summary.(field) + current.(field);
    end
    for field = minimumFields
        summary.(field) = min(summary.(field), current.(field));
    end
    summary.maximum_flux_correction_norm = max( ...
        summary.maximum_flux_correction_norm, ...
        current.maximum_flux_correction_norm);
end
end

function output = addPpDiagnostics(output, diagnostics)
fields = ["rho_floor", "p_floor", ...
    "reconstruction_pp_activation_count", "flux_pp_activation_count", ...
    "reconstruction_pp_min_theta", "flux_pp_min_theta", ...
    "minimum_reconstructed_density", "minimum_reconstructed_pressure", ...
    "invalid_reconstruction_count", "minimum_anchor_partial_density", ...
    "minimum_anchor_partial_pressure", "minimum_final_partial_density", ...
    "minimum_final_partial_pressure", "maximum_flux_correction_norm", ...
    "invalid_stage_count", "minimum_cell_density_by_stage", ...
    "minimum_cell_pressure_by_stage", "minimum_interface_density_by_stage", ...
    "minimum_interface_pressure_by_stage", ...
    "minimum_anchor_partial_density_by_stage", ...
    "minimum_anchor_partial_pressure_by_stage", ...
    "minimum_final_partial_density_by_stage", ...
    "minimum_final_partial_pressure_by_stage"];
for field = fields
    output.(field) = diagnostics.(field);
end
end

function closeIfOwned(modelName, wasLoaded)
if ~wasLoaded && bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end

function cleanup = keepHyperbolicModelsLoaded(boundary, modelRoot)
if boundary == "periodic_uniform_friction"
    cleanup = onCleanup(@() []);
    return
end
stepModel = "s12_euler_fvm_periodic_step_muscl_minmod_pp_ref";
stageModel = "s12_euler_ssprk3_periodic_ref";
stepWasLoaded = bdIsLoaded(stepModel);
stageWasLoaded = bdIsLoaded(stageModel);
load_system(fullfile(modelRoot, stepModel + ".slx"));
load_system(fullfile(modelRoot, stageModel + ".slx"));
cleanup = onCleanup(@() closeHyperbolicModels( ...
    stepModel, stageModel, stepWasLoaded, stageWasLoaded));
end

function closeHyperbolicModels(stepModel, stageModel, stepWasLoaded, stageWasLoaded)
if ~stepWasLoaded && bdIsLoaded(stepModel)
    close_system(stepModel, 0);
end
if ~stageWasLoaded && bdIsLoaded(stageModel)
    close_system(stageModel, 0);
end
end
