function profile = s12_fanno_analytical_profile(definition, lengthM, cellCount, quadratureNodes)
%S12_FANNO_ANALYTICAL_PROFILE Build matched conservative Fanno cell averages.
arguments
    definition (1,1) struct
    lengthM (1,1) double {mustBePositive}
    cellCount (1,1) double {mustBeInteger, mustBePositive}
    quadratureNodes (1,1) double {mustBeInteger, mustBePositive}
end
validateDefinition(definition);
darcyFactor = darcyFrictionFactor(definition);
cellEdges = linspace(0, lengthM, cellCount + 1);
stateAt = @(positions) conservativeAt(positions, definition, darcyFactor);
cellAverageState = s12_fanno_cell_average(stateAt, cellEdges, quadratureNodes);
cellCenters = 0.5 * (cellEdges(1:end-1) + cellEdges(2:end));
centerState = stateAt(cellCenters);
outletReference = fannoAt(lengthM, definition, darcyFactor);
profile = struct( ...
    "analytical_reference_id", "fanno_exact_relation_darcy.v1", ...
    "cell_average_reference_id", "gauss_legendre_conservative.v1", ...
    "initialization_id", "analytical_fanno_cell_average.v1", ...
    "length_m", lengthM, ...
    "darcy_friction_factor", darcyFactor, ...
    "cell_edges_m", cellEdges, ...
    "cell_centers_m", cellCenters, ...
    "cell_average_state", cellAverageState, ...
    "center_state", centerState, ...
    "outlet_reference", outletReference.outlet, ...
    "minimum_sonic_margin", sonicMargin(outletReference, lengthM));
end

function validateDefinition(definition)
required = ["gas_constant", "cp", "dynamic_viscosity", "diameter", ...
    "roughness", "inlet_static_pressure", "inlet_static_temperature", ...
    "mass_flow", "area", "gamma"];
if ~all(isfield(definition, required))
    error("S12:Fanno:InvalidInput", "Incomplete matched Fanno definition.");
end
values = cellfun(@(field) definition.(field), cellstr(required));
if any(~isfinite(values)) || any(values <= 0) || definition.gamma <= 1
    error("S12:Fanno:InvalidInput", "Invalid matched Fanno definition.");
end
end

function factor = darcyFrictionFactor(definition)
reynolds = definition.mass_flow * definition.diameter / ...
    (definition.dynamic_viscosity * definition.area);
factor = 1 / (-1.8 * log10(6.9 / reynolds + ...
    (definition.roughness / (3.7 * definition.diameter))^1.11))^2;
end

function states = conservativeAt(positions, definition, factor)
positions = reshape(positions, 1, []);
states = zeros(3, numel(positions));
for index = 1:numel(positions)
    reference = fannoAt(positions(index), definition, factor);
    outlet = reference.outlet;
    states(:, index) = [outlet.static_density; ...
        outlet.static_density * outlet.velocity; ...
        outlet.static_pressure / (definition.gamma - 1) + ...
        0.5 * outlet.static_density * outlet.velocity^2];
end
end

function reference = fannoAt(lengthM, definition, factor)
inletDensity = definition.inlet_static_pressure / ...
    (definition.gas_constant * definition.inlet_static_temperature);
inletSoundSpeed = sqrt(definition.gamma * definition.gas_constant * ...
    definition.inlet_static_temperature);
inletMach = definition.mass_flow / ...
    (inletDensity * inletSoundSpeed * definition.area);
reference = s12_fanno_reference(struct( ...
    "static_pressure", definition.inlet_static_pressure, ...
    "static_temperature", definition.inlet_static_temperature, ...
    "mach", inletMach, "gamma", definition.gamma, ...
    "gas_constant", definition.gas_constant, "area", definition.area, ...
    "diameter", definition.diameter, "length", lengthM, ...
    "darcy_friction_factor", factor));
end

function margin = sonicMargin(reference, lengthM)
margin = reference.remaining_length_to_choke / ...
    (reference.remaining_length_to_choke + lengthM);
end
