function metrics = s12_fanno_balance_metrics(input)
%S12_FANNO_BALANCE_METRICS Report steady balance-law metrics without clipping.
required = ["mass_flux", "total_enthalpy", "stagnation_temperature", ...
    "momentum_flux_in", "momentum_flux_out", ...
    "wall_momentum_source_integral", "state_change_residual"];
if ~isstruct(input) || ~all(isfield(input, required))
    error("S12:Fanno:InvalidInput", "Incomplete Fanno balance-law metric input.");
end
massFlux = row(input.mass_flux);
enthalpy = row(input.total_enthalpy);
stagnationTemperature = row(input.stagnation_temperature);
scalars = [input.momentum_flux_in, input.momentum_flux_out, ...
    input.wall_momentum_source_integral, input.state_change_residual];
if isempty(massFlux) || isempty(enthalpy) || isempty(stagnationTemperature) || ...
        any(~isfinite([massFlux, enthalpy, stagnationTemperature, scalars]))
    error("S12:Fanno:InvalidInput", "Fanno balance-law metrics must be finite.");
end
massScale = max(abs(mean(massFlux)), eps);
enthalpyScale = max(abs(mean(enthalpy)), eps);
momentumScale = max([abs(input.momentum_flux_in), abs(input.momentum_flux_out), ...
    abs(input.wall_momentum_source_integral), 1]);
metrics = struct( ...
    "normalized_state_residual", input.state_change_residual, ...
    "mass_flow_uniformity", max(abs(massFlux - mean(massFlux))) / massScale, ...
    "mass_balance_residual", abs(massFlux(end) - massFlux(1)) / massScale, ...
    "energy_balance_residual", max(abs(enthalpy - mean(enthalpy))) / enthalpyScale, ...
    "stagnation_temperature_spread", max(stagnationTemperature) - min(stagnationTemperature), ...
    "source_balanced_momentum_residual", abs( ...
        input.momentum_flux_out - input.momentum_flux_in - ...
        input.wall_momentum_source_integral) / momentumScale);
end

function values = row(values)
if ~isnumeric(values)
    error("S12:Fanno:InvalidInput", "Fanno metric vectors must be numeric.");
end
values = reshape(values, 1, []);
end
