function receipt = run_r2_matlab_psychoacoustic_audit(outputRoot)
%RUN_R2_MATLAB_PSYCHOACOUSTIC_AUDIT Recheck authorised R2 pairs in MATLAB.
%   This entry point intentionally does not accept or fabricate RPM/state
%   traces. It computes only digital-domain relative psychoacoustic metrics
%   for three existing R2 reference/candidate pairs. The source media remain
%   outside Git; outputRoot is an explicitly supplied external directory.

arguments
    outputRoot (1,:) char
end

if isfolder(outputRoot)
    error('s12:StageQ:R2MatlabOutputExists', ...
        'Refusing to overwrite an existing R2 MATLAB output directory.');
end
mkdir(outputRoot);

scriptRoot = fileparts(mfilename('fullpath'));
soundSimS12Root = fileparts(scriptRoot);
matlabAdapterRoot = fullfile(scriptRoot, '..', 'acoustic_comparator', 'matlab');
addpath(matlabAdapterRoot);
cleanupPath = onCleanup(@() rmpath(matlabAdapterRoot)); %#ok<NASGU>

cases = { ...
    struct( ...
        'case_id', 'ferrari_458_acceleration', ...
        'vehicle_id', 'ferrari_458', ...
        'scenario', 'acceleration', ...
        'reference_path', 'E:\Claude_allow\Download\s12-web-authorized-20260822\ferrari_458_italia.wav', ...
        'reference_sha256', '44b236ac66d3b2ea6b75a6e4e738c4a827172184473bca03806bb59d2828f59a', ...
        'reference_license', 'CC BY-SA 3.0', ...
        'candidate_path', fullfile(soundSimS12Root, ...
            'acoustic_identity_v015', 'docs', 'ferrari_458_ab.wav'), ...
        'candidate_sha256', '6d31eae59a0adcf85d9a194bab707302dbb5417e1c55bf268d63abbd199a5fee'), ...
    struct( ...
        'case_id', 'hellcat_launch', ...
        'vehicle_id', 'hellcat', ...
        'scenario', 'launch', ...
        'reference_path', 'E:\Claude_allow\Download\s12-web-authorized-20260822\hellcat_launching_challenger.wav', ...
        'reference_sha256', 'b5a23a855b80538edfdd3200d1a9e99aba0485d2c703abaef8e235652b7c73e6', ...
        'reference_license', 'CC BY-SA 4.0', ...
        'candidate_path', fullfile(soundSimS12Root, ...
            'acoustic_identity_v015', 'docs', 'hellcat_ab.wav'), ...
        'candidate_sha256', '1bb9027ffe864c5fcb8aec03c1f2f9d121cb6923ec3988eb00d656e045169061'), ...
    struct( ...
        'case_id', 'rx7_fd_full_pull', ...
        'vehicle_id', 'rx7_fd', ...
        'scenario', 'full_pull', ...
        'reference_path', 'E:\Claude_allow\Download\s12-rx7sim-source-audit-20260823\decoded_wav\rx7sim_exhaust_revLong01.wav', ...
        'reference_sha256', '8fb34a9f7a29106f84aa976fb98096898fc3bb3952ea95a865ad7314d85e1ccb', ...
        'reference_license', 'CC BY-NC-SA 4.0', ...
        'candidate_path', fullfile(soundSimS12Root, ...
            'acoustic_identity_v015', 'docs', 'rx7_fd_ab.wav'), ...
        'candidate_sha256', '03ffffc1f3937eec52b0dc841e1b54c6c9f90ef4a0a3978e4c0db99f80603fd8') ...
    };

metricNames = { ...
    'loudness_sone', 'sharpness_acum', 'roughness_asper', ...
    'fluctuation_vacil', 'tone_to_noise_ratio_db', ...
    'tone_to_noise_frequency_hz', 'prominence_ratio_db', ...
    'prominence_frequency_hz'};
results = cell(1, numel(cases));
for index = 1:numel(cases)
    c = cases{index};
    if ~isfile(c.reference_path)
        error('s12:StageQ:R2ReferenceMissing', 'Reference file is missing: %s', c.reference_path);
    end
    if ~isfile(c.candidate_path)
        error('s12:StageQ:R2CandidateMissing', 'Candidate file is missing: %s', c.candidate_path);
    end

    [reference, referenceFs] = audioread(c.reference_path);
    [candidate, candidateFs] = audioread(c.candidate_path);
    reference = mean(double(reference), 2);
    candidate = mean(double(candidate), 2);
    if candidateFs ~= referenceFs
        candidate = resample(candidate, referenceFs, candidateFs);
    end

    windowSamples = min([numel(reference), numel(candidate), round(5 * referenceFs)]);
    if windowSamples < 2
        error('s12:StageQ:R2WindowTooShort', 'R2 comparison window is too short: %s', c.case_id);
    end
    reference = reference(1:windowSamples);
    candidate = candidate(1:windowSamples);

    caseRoot = fullfile(outputRoot, c.case_id);
    referenceResult = s12_psychoacoustic_analysis( ...
        struct('signal', reference, 'sample_rate_hz', referenceFs), ...
        fullfile(caseRoot, 'reference'));
    candidateResult = s12_psychoacoustic_analysis( ...
        struct('signal', candidate, 'sample_rate_hz', referenceFs), ...
        fullfile(caseRoot, 'candidate'));
    residual = struct();
    for metricIndex = 1:numel(metricNames)
        name = metricNames{metricIndex};
        referenceValue = referenceResult.metrics.(name);
        candidateValue = candidateResult.metrics.(name);
        residual.(name) = candidateValue - referenceValue;
    end

    results{index} = struct( ...
        'case_id', c.case_id, ...
        'vehicle_id', c.vehicle_id, ...
        'scenario', c.scenario, ...
        'reference_path', c.reference_path, ...
        'reference_sha256', c.reference_sha256, ...
        'reference_license', c.reference_license, ...
        'candidate_path', c.candidate_path, ...
        'candidate_sha256', c.candidate_sha256, ...
        'sample_rate_hz', referenceFs, ...
        'window', 'first_5_seconds_common_window', ...
        'channel_policy', 'downmix_to_mono_for_metric_only', ...
        'resample_policy', 'candidate_resampled_in_memory_to_reference_rate_without_gain_eq_or_agc', ...
        'reference_metrics', referenceResult.metrics, ...
        'candidate_metrics', candidateResult.metrics, ...
        'candidate_minus_reference', residual, ...
        'order_status', 'NOT_EVALUATED_WITHOUT_SYNCHRONIZED_RPM_TRACE', ...
        'state_status', 'MISSING_SYNCHRONIZED_RPM_LOAD_THROTTLE_GEAR_SHIFT', ...
        'qualification', 'R2_LIMITED_COMPARISON_ONLY', ...
        'automatic_tuning_eligible', false, ...
        'parameter_recommendations', [], ...
        'human_feedback_status', 'NOT_PROVIDED');
end

receipt = struct( ...
    'schema_version', 's12-stage-q-r2-matlab-psychoacoustic-audit-v1', ...
    'status', 'R2_LIMITED_COMPARISON_COMPLETE', ...
    'matlab_release', version('-release'), ...
    'analysis_signal', 'unaltered digital-domain signal; not calibrated SPL', ...
    'toolchain', {{'acousticLoudness', 'acousticSharpness', 'acousticRoughness', ...
        'acousticFluctuation', 'acousticToneToNoiseRatio', 'acousticProminenceRatio'}}, ...
    'case_count', numel(results), ...
    'window_contract', 'first 5 seconds of each common pair; no time/state alignment claim', ...
    'results', {results}, ...
    'limitations', {{ ...
        'All three references are R2 and lack synchronized RPM/load/throttle/gear/shift traces.', ...
        'No order-RPM map, OEM absolute threshold, automatic tuning, or Profile Candidate is produced.', ...
        'Reference and candidate microphone/AGC/stock-state differences remain uncertainty sources.', ...
        'Human Jovi feedback is not included.' ...
        }}, ...
    'automatic_tuning_eligible', false, ...
    'profile_candidate_ready', false);
s12_export_matlab_comparator_result(receipt, outputRoot, 'matlab_r2_psychoacoustic_audit');
end
