function frame = s12_v12_model_source_step(packed, profileId)
%S12_V12_MODEL_SOURCE_STEP Fixed-frame Simulink source adapter.

persistent activeProfileId profile context lastTime
if ~isnumeric(packed) || ~isequal(size(packed), [9, 1]) || ...
        any(~isfinite(packed), "all")
    error("S12:EngineSoundV12:ModelSource", ...
        "Model source input must be one finite [9,1] vector.");
end
profileId = string(profileId);
time = packed(9);
if isempty(activeProfileId) || activeProfileId ~= profileId || ...
        isempty(lastTime) || time <= lastTime
    profilePath = fullfile(fileparts(fileparts(mfilename("fullpath"))), ...
        "vehicles", profileId, "source_profile.json");
    if ~isfile(profilePath)
        error("S12:EngineSoundV12:ModelSource", ...
            "Model source profile does not exist.");
    end
    profile = jsondecode(fileread(profilePath));
    s12_v12_validate_source_profile(profile);
    activeProfileId = profileId;
    context = [];
end

afterfireKinds = ["none", "upshift_bark", ...
    "downshift_blip_pop", "overrun_crackle"];
afterfireIndex = packed(7) + 1;
if fix(afterfireIndex) ~= afterfireIndex || ...
        afterfireIndex < 1 || afterfireIndex > numel(afterfireKinds)
    error("S12:EngineSoundV12:ModelSource", ...
        "afterfire code must be an integer from zero through three.");
end
state = struct( ...
    "rpm", packed(1), ...
    "load", packed(2), ...
    "throttle", packed(3), ...
    "acceleration", packed(4), ...
    "shift_event", packed(5), ...
    "shift_progress", packed(6), ...
    "afterfire_kind", afterfireKinds(afterfireIndex), ...
    "afterfire_progress", packed(8));
[frame, context] = s12_v12_render_pre_ptr_frame( ...
    state, profile, context, 48000, 960, profileId);
lastTime = time;
end
