function identity = s12_v12_validate_engine_identity_profile(profile)
%S12_V12_VALIDATE_ENGINE_IDENTITY_PROFILE Validate synthetic v0.4 identity data.

required = ["schema_version", "profile_id", "synthetic", "engine_type", ...
    "cylinder_count", "combustion_type", "rpm_limit", "firing_character", ...
    "order_profile", "harmonic_profile", "transient_profile", ...
    "mechanical_noise_profile", "turbo_or_supercharger_profile", ...
    "acoustic_color_profile"];
if ~isstruct(profile) || ~isscalar(profile) || ~hasExactFields(profile, required) || ...
        ~isfield(profile, "schema_version") || string(profile.schema_version) ~= ...
            "s12-engine-identity-profile-0.4" || ~isfield(profile, "synthetic") || ...
        profile.synthetic ~= true
    profileError("Profile root is invalid.");
end

identity = struct();
if ~((ischar(profile.profile_id) && isrow(profile.profile_id)) || ...
        (isstring(profile.profile_id) && isscalar(profile.profile_id)))
    profileError("profile_id must be one text value.");
end
identity.profile_id = string(profile.profile_id);
if ~ismember(identity.profile_id, ...
        ["hellcat_2022_stock", "ferrari_458_stock", "rx7_fd_1991_stock", ...
        "gtr_r35_2007_stock", "supra_jza80_rz_stock", "lexus_lfa_stock"])
    profileError("profile_id is unsupported.");
end
identity.engine_type = enumParameter(profile.engine_type, "engine_type", ...
    ["supercharged_cross_plane_v8", "naturally_aspirated_flat_plane_v8", ...
    "twin_rotor_turbo", "twin_turbo_v6", "twin_turbo_inline6", ...
    "naturally_aspirated_v10"]);
identity.cylinder_count = numericParameter(profile.cylinder_count, ...
    "cylinder_count", 1, 12, true);
identity.combustion_type = enumParameter(profile.combustion_type, ...
    "combustion_type", ["cross_plane_piston", "flat_plane_piston", ...
    "rotary_three_chamber", "even_fire_piston", "v10_even_fire_piston"]);
identity.rpm_limit = numericParameter(profile.rpm_limit, "rpm_limit", 1000, 12000, true);

identity.firing_character = struct( ...
    "pulse_shape", enumParameter(profile.firing_character.pulse_shape, "pulse_shape", ...
        ["cross_plane_uneven_bank_pulse", "flat_plane_sharp_pulse", ...
        "rotary_chamber_pulse_train", "even_fire_v6_pulse", ...
        "inline6_smooth_pulse", "v10_high_rev_pulse"]), ...
    "pulse_width", numericParameter(profile.firing_character.pulse_width, "pulse_width", 0, 1, false), ...
    "bank_asymmetry", numericParameter(profile.firing_character.bank_asymmetry, "bank_asymmetry", 0, 1, false));
identity.order_profile = struct( ...
    "primary_order", numericParameter(profile.order_profile.primary_order, "primary_order", 0.5, 64, false), ...
    "secondary_order", numericParameter(profile.order_profile.secondary_order, "secondary_order", 0.5, 64, false), ...
    "high_order", numericParameter(profile.order_profile.high_order, "high_order", 0.5, 64, false));
identity.harmonic_profile = struct( ...
    "base_gain", numericParameter(profile.harmonic_profile.base_gain, "base_gain", 0, 1, false), ...
    "high_rpm_gain", numericParameter(profile.harmonic_profile.high_rpm_gain, "high_rpm_gain", 0, 1, false), ...
    "rpm_exponent", numericParameter(profile.harmonic_profile.rpm_exponent, "rpm_exponent", 0.1, 4, false), ...
    "high_frequency_order", numericParameter(profile.harmonic_profile.high_frequency_order, "high_frequency_order", 0.5, 80, false));
identity.transient_profile = struct( ...
    "attack_gain", numericParameter(profile.transient_profile.attack_gain, "attack_gain", 0, 1, false), ...
    "release_per_frame", numericParameter(profile.transient_profile.release_per_frame, "release_per_frame", 0, 1, false), ...
    "load_coupling", numericParameter(profile.transient_profile.load_coupling, "load_coupling", 0, 1, false));
identity.mechanical_noise_profile = struct( ...
    "base_gain", numericParameter(profile.mechanical_noise_profile.base_gain, "mechanical base_gain", 0, 1, false), ...
    "mechanical_order", numericParameter(profile.mechanical_noise_profile.mechanical_order, "mechanical_order", 0.5, 64, false), ...
    "roughness", numericParameter(profile.mechanical_noise_profile.roughness, "roughness", 0, 1, false));
identity.turbo_or_supercharger_profile = struct( ...
    "architecture", enumParameter(profile.turbo_or_supercharger_profile.architecture, "induction architecture", ...
        ["none", "supercharger", "twin_turbo"]), ...
    "drive_ratio", numericParameter(profile.turbo_or_supercharger_profile.drive_ratio, "drive_ratio", 0, 8, false), ...
    "whine_gain", numericParameter(profile.turbo_or_supercharger_profile.whine_gain, "whine_gain", 0, 1, false), ...
    "spool_rate", numericParameter(profile.turbo_or_supercharger_profile.spool_rate, "spool_rate", 0, 1, false), ...
    "turbine_gain", numericParameter(profile.turbo_or_supercharger_profile.turbine_gain, "turbine_gain", 0, 1, false));
identity.acoustic_color_profile = struct( ...
    "low_band_gain", numericParameter(profile.acoustic_color_profile.low_band_gain, "low_band_gain", 0, 1, false), ...
    "mid_band_gain", numericParameter(profile.acoustic_color_profile.mid_band_gain, "mid_band_gain", 0, 1, false), ...
    "high_band_gain", numericParameter(profile.acoustic_color_profile.high_band_gain, "high_band_gain", 0, 1, false));
validateEngineTopology(identity);
identity.provenance = "C/synthetic/uncalibrated";
end

function value = numericParameter(record, label, lower, upper, integerRequired)
validateParameterRecord(record, label);
value = record.value;
if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
        value < lower || value > upper || (integerRequired && value ~= round(value))
    profileError("%s is outside its identity contract.", label);
end
value = double(value);
end

function value = enumParameter(record, label, allowed)
validateParameterRecord(record, label);
if ~((ischar(record.value) && isrow(record.value)) || ...
        (isstring(record.value) && isscalar(record.value)))
    profileError("%s must be one text enum value.", label);
end
value = string(record.value);
if ~ismember(value, allowed)
    profileError("%s is unsupported.", label);
end
end

function validateParameterRecord(record, label)
required = ["value", "unit", "range", "source_level", "source", ...
    "source_url", "source_scope", "verification_state"];
if ~isstruct(record) || ~isscalar(record) || ~hasExactFields(record, required) || ...
        string(record.source_level) ~= "C" || string(record.source) ~= "synthetic" || ...
        string(record.source_url) ~= "" || ...
        string(record.verification_state) ~= "synthetic_assumption" || ...
        ~((ischar(record.unit) && isrow(record.unit)) || ...
        (isstring(record.unit) && isscalar(record.unit))) || ...
        ~((ischar(record.source_scope) && isrow(record.source_scope)) || ...
        (isstring(record.source_scope) && isscalar(record.source_scope))) || ...
        strlength(string(record.source_scope)) == 0 || numel(record.range) < 2
    profileError("%s lacks valid C/synthetic provenance.", label);
end
end

function validateEngineTopology(identity)
switch identity.engine_type
    case "supercharged_cross_plane_v8"
        valid = identity.cylinder_count == 8 && ...
            identity.combustion_type == "cross_plane_piston" && ...
            identity.turbo_or_supercharger_profile.architecture == "supercharger";
    case "naturally_aspirated_flat_plane_v8"
        valid = identity.cylinder_count == 8 && ...
            identity.combustion_type == "flat_plane_piston" && ...
            identity.turbo_or_supercharger_profile.architecture == "none";
    case "twin_rotor_turbo"
        valid = identity.cylinder_count == 2 && ...
            identity.combustion_type == "rotary_three_chamber" && ...
            identity.turbo_or_supercharger_profile.architecture == "twin_turbo";
    case "twin_turbo_v6"
        valid = identity.cylinder_count == 6 && ...
            identity.combustion_type == "even_fire_piston" && ...
            identity.turbo_or_supercharger_profile.architecture == "twin_turbo";
    case "twin_turbo_inline6"
        valid = identity.cylinder_count == 6 && ...
            identity.combustion_type == "even_fire_piston" && ...
            identity.turbo_or_supercharger_profile.architecture == "twin_turbo";
    case "naturally_aspirated_v10"
        valid = identity.cylinder_count == 10 && ...
            identity.combustion_type == "v10_even_fire_piston" && ...
            identity.turbo_or_supercharger_profile.architecture == "none";
    otherwise
        valid = false;
end
if ~valid
    profileError("Engine identity topology is inconsistent.");
end
end

function value = hasExactFields(record, required)
value = isequal(sort(string(fieldnames(record))), sort(required(:)));
end

function profileError(message, varargin)
error("S12:EngineIdentity:Profile", message, varargin{:});
end
