function plan = s12_sound_playground_runtime_proof_plan(runId)
%S12_SOUND_PLAYGROUND_RUNTIME_PROOF_PLAN Plan a temporary-candidate proof without runtime execution.

if nargin ~= 1 || isempty(regexp(char(string(runId)), "^[A-Za-z][A-Za-z0-9_]{0,47}$", "once"))
    error("S12:Playground:RunId", "Runtime Proof run ID must be a filesystem-safe identifier.");
end
runId = string(runId);
portContract = s12_sound_playground_port_contract();
runtime = s12_sound_playground_runtime_paths(runId, "runtime_proof");
modelName = "S12_Sound_Playground_RUNTIME_PROOF_TMP";
candidatePath = fullfile(runtime.temporary_root, modelName + ".slx");
plan = struct( ...
    "schema", "s12.simulink.playground.runtime-proof-plan.v1", ...
    "run_id", runId, ...
    "execution_policy", "MANUAL_RUNTIME_REQUIRED", ...
    "runtime", runtime, ...
    "source_tree", s12_sound_playground_source_tree_sha256(), ...
    "artifacts", portContract.artifacts, ...
    "port_contract", portContract, ...
    "signal_contract", s12_sound_playground_signal_contract(), ...
    "temporary", struct("root", runtime.temporary_root, "model_name", modelName, ...
        "model_path", candidatePath, "failure_report_path", fullfile(runtime.temporary_root, "failure_report.json")), ...
    "candidate", struct("model_name", modelName, "path", candidatePath, ...
        "role", "RUN_SPECIFIC_TEMPORARY_CANDIDATE", "mutable", true), ...
    "runtime_proof_report_path", fullfile(runtime.transaction_root, "runtime_proof_report.json"));
end
