function params = s12_sound_playground_parameters(overrides)
%S12_SOUND_PLAYGROUND_PARAMETERS Synthetic-only v0.9 tuning defaults.
% This adapter is isolated from the frozen PTR/radiation/runtime numerical core.

params = struct( ...
    "version", "Synthetic Engine Sound Simulink Playground v0.9", ...
    "synthetic", true, ...
    "calibrated", false, ...
    "offline", true, ...
    "realtime_qualified", false, ...
    "sample_rate_hz", 48000, ...
    "frame_samples", 960, ...
    "rpm", 800, ...
    "load", 0.10, ...
    "acceleration_mps2", 0.0, ...
    "throttle", 0.10, ...
    "cylinder_count", 4, ...
    "firing_order", [1, 3, 4, 2], ...
    "order_gain", [1.00, 0.70, 0.40, 0.25], ...
    "pipe_length_m", 1.50, ...
    "area_m2", 0.020, ...
    "reflection_coefficient", 0.35, ...
    "damping", 0.15, ...
    "gain_db", -12.0, ...
    "source_level", "C", ...
    "provenance", "synthetic tuning defaults; not OEM or vehicle-calibrated");

if nargin == 1
    names = fieldnames(overrides);
    for index = 1:numel(names)
        name = names{index};
        if ~isfield(params, name)
            error("S12:Playground:UnknownParameter", "Unknown parameter: %s", name);
        end
        params.(name) = overrides.(name);
    end
end

validateattributes(params.rpm, {'numeric'}, {"scalar", "finite", ">=", 800, "<=", 7000});
validateattributes(params.load, {'numeric'}, {"scalar", "finite", ">=", 0, "<=", 1});
validateattributes(params.acceleration_mps2, {'numeric'}, {"scalar", "finite", ">=", -2, "<=", 5});
validateattributes(params.throttle, {'numeric'}, {"scalar", "finite", ">=", 0, "<=", 1});
if params.cylinder_count ~= 4
    error("S12:Playground:CylinderScope", "v0.9 supports exactly four synthetic cylinders.");
end
if numel(params.firing_order) ~= 4
    error("S12:Playground:FiringOrder", "Firing order must contain exactly four entries.");
end
validateattributes(params.firing_order, {'numeric'}, {"vector", "finite", "integer"});
if ~isequal(sort(reshape(params.firing_order, 1, [])), 1:4)
    error("S12:Playground:FiringOrder", "Firing order must be a permutation of 1:4.");
end
validateattributes(params.order_gain, {'numeric'}, {"vector", "numel", 4, "finite", ">=", 0});
validateattributes(params.pipe_length_m, {'numeric'}, {"scalar", "finite", ">", 0});
validateattributes(params.area_m2, {'numeric'}, {"scalar", "finite", ">", 0});
validateattributes(params.reflection_coefficient, {'numeric'}, {"scalar", "finite", ">=", 0, "<=", 0.95});
validateattributes(params.damping, {'numeric'}, {"scalar", "finite", ">=", 0, "<=", 0.95});
assert(params.sample_rate_hz == 48000 && params.frame_samples == 960, ...
    "S12:Playground:AudioFormat", "v0.9 is fixed at 48 kHz and 960 samples per frame.");
end
