function s12_sound_playground_validate_pcm_metrics(metrics, expectedFrames, expectedDuration)
%S12_SOUND_PLAYGROUND_VALIDATE_PCM_METRICS Fail closed before WAV emission.

contract = s12_sound_playground_pcm_metrics_contract();
if nargin < 3
    expectedDuration = contract.duration_s;
end
checks = [ ...
    metrics.actual_frame_count == expectedFrames, ...
    metrics.pcm_sample_count == expectedFrames * contract.frame_samples, ...
    metrics.channels == contract.channels, metrics.sample_rate_hz == contract.sample_rate_hz, ...
    metrics.finite, metrics.clipping_count == contract.clipping_count_must_equal, ...
    metrics.peak < contract.peak_must_be_less_than, abs(metrics.dc) <= contract.dc_absolute_limit, ...
    metrics.boundary_last_to_first <= contract.boundary_jump_absolute_limit, ...
    abs(metrics.duration_s - expectedDuration) <= eps(expectedDuration)];
if ~all(checks)
    error("S12:Playground:PcmValidation", "PCM qualification metrics failed: %s", jsonencode(metrics));
end
end
