function preflight = s12_sound_playground_runtime_proof_preflight(plan)
%S12_SOUND_PLAYGROUND_RUNTIME_PROOF_PREFLIGHT Close exact stale handles, self-test JSON, then hash canonical SLX.

failedTransaction = fullfile(plan.runtime.runtime_base, "runtime_proof_20260727_081025_562");
if isfolder(failedTransaction)
    staleCleanup = s12_sound_playground_close_owned_json_temp_handles(failedTransaction);
else
    staleCleanup = struct("matched_handle_ids", zeros(1, 0), "closed_handle_ids", zeros(1, 0), ...
        "close_failures", struct("file_id", {}, "status", {}), "temporary_files_before", strings(1, 0), ...
        "deleted_temporary_paths", strings(1, 0), "remaining_matching_handles", zeros(1, 0), ...
        "temporary_files_after", strings(1, 0));
end
selftest = s12_sound_playground_atomic_write_json_selftest(plan.runtime.runtime_base, plan.run_id);
canonical = plan.artifacts.workspace_unvalidated_intermediate;
canonicalSha256 = upper(s12_sound_playground_sha256(canonical.path));
expectedCanonicalSha256 = "43241395121AD9D71073B030B328195D7D0F28140DEAB8CED41681D1DB853CC5";
s12_sound_playground_require_sha256_equal(canonicalSha256, expectedCanonicalSha256, ...
    "Canonical SLX SHA-256 changed before Runtime Proof");
s12_sound_playground_require_sha256_equal(canonicalSha256, canonical.sha256, ...
    "Canonical SLX SHA-256 differs from the artifact contract");
preflight = struct("status", "ATOMIC_WRITER_SELFTEST_PASSED", "failed_transaction_status", ...
    "FAILED_AT_STAGE_EVIDENCE_WRITE", "failed_transaction_root", string(failedTransaction), ...
    "stale_handle_cleanup", staleCleanup, "atomic_writer_selftest", selftest, ...
    "canonical_slx_path", canonical.path, "canonical_sha256_before", canonicalSha256, ...
    "canonical_sha256_after", "");
end
