function s12_sound_playground_validate_dimensions(observed, contract)
%S12_SOUND_PLAYGROUND_VALIDATE_DIMENSIONS Reject variable or wrong frame shapes.

if nargin < 2
    contract = s12_sound_playground_signal_contract();
end
expected = struct( ...
    "configuration", contract.configuration.shape, ...
    "configuration_vehicle_input", contract.configuration.shape, ...
    "configuration_vehicle_output", contract.configuration.shape, ...
    "configuration_engine_input", contract.configuration.shape, ...
    "excitation", contract.excitation.shape, ...
    "pressure", contract.pressure.shape, ...
    "pcm", contract.pcm.shape);
names = fieldnames(expected);
for index = 1:numel(names)
    name = names{index};
    if ~isfield(observed, name) || ~isequal(observed.(name), expected.(name))
        error("S12:Playground:DimensionContract", "Dimension contract mismatch: %s", name);
    end
end
end
