function contract = s12_sound_playground_port_contract()
%S12_SOUND_PLAYGROUND_PORT_CONTRACT Fixed topology and explicit artifact roles.

root = string(fileparts(mfilename("fullpath")));
contract.version = "v0.9-v7-offline-closeout-audit-v6";
contract.artifacts = struct( ...
    "historical_pre_repair_invalid", artifact( ...
        "audit-package/evidence/S12_Sound_Playground_PRE_REPAIR_INVALID.slx", ...
        "FA91F46A2F8F6D78586FAE407E795BCEB99AD529F76925A4AF806F9AC73595C0", 73921, ...
        "HISTORICAL_PRE_REPAIR_INVALID_AUDIT_EVIDENCE", false, ["read", "package"]), ...
    "workspace_unvalidated_intermediate", artifact( ...
        fullfile(root, "S12_Sound_Playground.slx"), ...
        "43241395121AD9D71073B030B328195D7D0F28140DEAB8CED41681D1DB853CC5", 87428, ...
        "WORKSPACE_UNVALIDATED_INTERMEDIATE", false, ["read", "package"]), ...
    "temporary_candidate", artifact( ...
        "<external-runtime-root>/temporary/candidate.slx", "", 0, ...
        "TEMPORARY_REPAIRED_CANDIDATE", true, ["create", "inspect", "compile", "delete_on_failure"]), ...
    "formal_repaired_candidate", artifact( ...
        fullfile(root, "S12_Sound_Playground_repaired_candidate.slx"), "", 0, ...
        "FORMAL_REPAIRED_CANDIDATE", true, ["promote", "qualify", "package"]), ...
    "future_canonical", artifact( ...
        fullfile(root, "S12_Sound_Playground.slx"), "", 0, ...
        "FUTURE_CANONICAL_AFTER_SEPARATE_MIGRATION", true, "separate_authorized_canonical_migration"));
contract.subsystems = struct( ...
    "Dashboard", ports(0, 1, strings(1, 0), "Configuration"), ...
    "VehicleState", ports(1, 1, "Configuration", "Packed"), ...
    "EngineExcitation", ports(1, 2, "Packed", ["Excitation", "Packed Out"]), ...
    "PtrRadiationTuningAdapter", ports(2, 2, ["Excitation", "Packed"], ["Pressure", "Packed Out"]), ...
    "AudioRenderer", ports(2, 1, ["Pressure", "Packed"], "PCM"));
contract.top_level_connections = [ ...
    link("Dashboard.Configuration", "Vehicle State.Configuration"), ...
    link("Vehicle State.Packed", "Engine Excitation.Packed"), ...
    link("Engine Excitation.Excitation", "PTR Radiation Tuning Adapter.Excitation"), ...
    link("Engine Excitation.Packed Out", "PTR Radiation Tuning Adapter.Packed"), ...
    link("PTR Radiation Tuning Adapter.Pressure", "Audio Renderer.Pressure"), ...
    link("PTR Radiation Tuning Adapter.Packed Out", "Audio Renderer.Packed"), ...
    link("Audio Renderer.PCM", "Qualification PCM Sink.PCM"), ...
    link("Audio Renderer.PCM", "Optional Device Output.PCM")];
end

function value = artifact(path, sha256, sizeBytes, role, mutable, allowedOperations)
value = struct("path", string(path), "sha256", string(sha256), "size_bytes", sizeBytes, ...
    "role", string(role), "mutable", logical(mutable), "allowed_operations", string(allowedOperations));
end

function value = ports(inputs, outputs, inputNames, outputNames)
value = struct("inputs", inputs, "outputs", outputs, ...
    "input_names", string(inputNames), "output_names", string(outputNames));
end

function value = link(source, destination)
value = struct("source", string(source), "destination", string(destination));
end
