function interfaces = s12_sound_playground_function_interfaces()
%S12_SOUND_PLAYGROUND_FUNCTION_INTERFACES Fixed chart I/O expected at runtime.

signal = s12_sound_playground_signal_contract();
interfaces.EngineExcitation = struct( ...
    "inputs", struct("packed", signal.configuration.shape, "reset", [1, 1]), ...
    "input_order", ["packed", "reset"], "outputs", struct("excitation", signal.excitation.shape, ...
    "packedOut", signal.configuration.shape), "output_order", ["excitation", "packedOut"]);
interfaces.PtrRadiationTuningAdapter = struct( ...
    "inputs", struct("excitation", signal.excitation.shape, "packed", signal.configuration.shape, "reset", [1, 1]), ...
    "input_order", ["excitation", "packed", "reset"], "outputs", struct("pressure", signal.pressure.shape, ...
    "packedOut", signal.configuration.shape), "output_order", ["pressure", "packedOut"]);
interfaces.AudioRenderer = struct( ...
    "inputs", struct("pressure", signal.pressure.shape, "packed", signal.configuration.shape), ...
    "input_order", ["pressure", "packed"], "outputs", struct("pcm", signal.pcm.shape), "output_order", "pcm");
interfaces.status = "REQUIRES_CONTROLLED_RUNTIME_CONFIRMATION";
interfaces.reset = struct("mechanism", "first_chart_invocation_per_simulation", ...
    "uses_clear_all", false, "status", "REQUIRES_CONTROLLED_RUNTIME_CONFIRMATION");
end
