function result = s12_sound_playground_run_case(name, durationSeconds, outputDirectory, overrides)
%S12_SOUND_PLAYGROUND_RUN_CASE Direct MATLAB reference, not Simulink evidence.

if nargin < 2
    durationSeconds = 5;
end
if nargin < 3
    outputDirectory = fullfile(fileparts(mfilename("fullpath")), "simulation_result");
end
if nargin < 4
    overrides = struct();
end
if isfolder(outputDirectory) && ~isempty(dir(fullfile(outputDirectory, "*")))
    entries = dir(outputDirectory);
    if any(~ismember({entries.name}, {".", ".."}))
        error("S12:Playground:OutputExists", "Refusing to overwrite %s", outputDirectory);
    end
end
if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

[pcm, trace, params] = s12_sound_playground_render_case(name, durationSeconds, overrides);
wavPath = fullfile(outputDirectory, lower(string(name)) + ".wav");
audiowrite(wavPath, pcm, params.sample_rate_hz, "BitsPerSample", 24);

tracePath = fullfile(outputDirectory, "runtime_trace.csv");
writetable(struct2table(trace), tracePath);
sourceDirectory = fileparts(mfilename("fullpath"));
sourceHashes = struct( ...
    "excitation", s12_sound_playground_sha256(fullfile(sourceDirectory, "s12_sound_playground_excitation_step.m")), ...
    "ptr_tuning_adapter", s12_sound_playground_sha256(fullfile(sourceDirectory, "s12_sound_playground_ptr_tuning_step.m")), ...
    "renderer", s12_sound_playground_sha256(fullfile(sourceDirectory, "s12_sound_playground_render_case.m")));
metadata = struct( ...
    "source", "direct_matlab_reference", ...
    "generator_version", params.version, ...
    "architecture", "engine_excitation_to_synthetic_tuning_adapter_to_renderer", ...
    "synthetic", true, ...
    "calibrated", false, ...
    "offline", true, ...
    "realtime_qualified", false, ...
    "source_level", "C", ...
    "sample_rate_hz", params.sample_rate_hz, ...
    "bit_depth", 24, ...
    "channels", 2, ...
    "case", string(name), ...
    "duration_seconds", size(pcm, 1) / params.sample_rate_hz, ...
    "peak", max(abs(pcm), [], "all"), ...
    "clipping_samples", sum(abs(pcm) >= 1, "all"), ...
    "wav_sha256", s12_sound_playground_sha256(wavPath), ...
    "generator_source_hashes", sourceHashes, ...
    "frozen_ptr_radiation_hash", "0f4b2ca494cd44f79d05968513759578d04e6ab38b1ee37f7621158abb0d2d6f", ...
    "frozen_core_modified", false);
snapshot = struct("parameters", params, "scenario", string(name), "duration_seconds", durationSeconds);
s12_sound_playground_atomic_write_json(fullfile(outputDirectory, "metadata.json"), metadata);
s12_sound_playground_atomic_write_json(fullfile(outputDirectory, "parameter_snapshot.json"), snapshot);
result = struct("output_directory", string(outputDirectory), "wav_path", string(wavPath), ...
    "wav_sha256", metadata.wav_sha256, "metadata", metadata, "evidence_scope", "DIRECT_REFERENCE_ONLY");
end
