function scripts = s12_sound_playground_function_scripts()
%S12_SOUND_PLAYGROUND_FUNCTION_SCRIPTS Generate chart code from one mapping.

signal = s12_sound_playground_signal_contract();
index = signal.indices;
engine = "function [excitation, packedOut] = fcn(packed, reset)" + newline + "%#codegen" + newline + ...
    "excitation = s12_sound_playground_excitation_step(packed(" + string(index.rpm) + "), packed(" + ...
    string(index.load) + "), packed(" + string(index.acceleration) + "), packed(" + ...
    string(index.throttle) + "), packed(" + string(index.cylinder_count) + "), packed(" + ...
    string(index.firing_order(1)) + ":" + string(index.firing_order(end)) + "), packed(" + ...
    string(index.order_gain(1)) + ":" + string(index.order_gain(end)) + "), reset);" + newline + ...
    "packedOut = packed;" + newline + "end" + newline;
ptr = "function [pressure, packedOut] = fcn(excitation, packed, reset)" + newline + "%#codegen" + newline + ...
    "pressure = s12_sound_playground_ptr_tuning_step(excitation, packed(" + string(index.pipe_length) + ...
    "), packed(" + string(index.area) + "), packed(" + string(index.reflection) + "), packed(" + ...
    string(index.damping) + "), reset);" + newline + "packedOut = packed;" + newline + "end" + newline;
renderer = "function pcm = fcn(pressure, packed)" + newline + "%#codegen" + newline + ...
    "gain = 10^(packed(" + string(index.gain_db) + ") / 20);" + newline + ...
    "pcm = gain * [pressure, pressure];" + newline + "end" + newline;
scripts = struct("engine", engine, "ptr", ptr, "renderer", renderer);
end
