function metrics = s12_sound_playground_measure_pcm(pcm, expectedFrames)
%S12_SOUND_PLAYGROUND_MEASURE_PCM Measure normalized two-channel PCM only.

signal = s12_sound_playground_signal_contract();
contract = s12_sound_playground_pcm_metrics_contract();
if ~isequal(size(pcm), [expectedFrames * signal.frame_samples, contract.channels])
    error("S12:Playground:PcmMetricsShape", "Normalized PCM has unexpected shape %s.", mat2str(size(pcm)));
end
firstSamples = pcm(1:signal.frame_samples:end, :);
lastSamples = pcm(signal.frame_samples:signal.frame_samples:end, :);
if expectedFrames < 2
    boundaryJump = 0;
else
    boundaryJump = max(abs(firstSamples(2:end, :) - lastSamples(1:end - 1, :)), [], "all");
end
metrics = struct( ...
    "actual_frame_count", size(pcm, 1) / signal.frame_samples, ...
    "pcm_sample_count", size(pcm, 1), "channels", size(pcm, 2), ...
    "sample_rate_hz", contract.sample_rate_hz, ...
    "duration_s", size(pcm, 1) / contract.sample_rate_hz, ...
    "peak", max(abs(pcm), [], "all"), "rms", rms(pcm, "all"), ...
    "dc", mean(pcm, "all"), "boundary_last_to_first", boundaryJump, ...
    "clipping_count", sum(abs(pcm) >= 1, "all"), ...
    "finite", all(isfinite(pcm), "all"), ...
    "underrun", "NOT_APPLICABLE_TO_TO_WORKSPACE_QUALIFICATION");
end
