function modes = s12_sound_playground_modes()
%S12_SOUND_PLAYGROUND_MODES Hardware-independent qualification versus audition.

modes.qualification = struct( ...
    "name", "qualification", "audio_device_writer_enabled", false, ...
    "pcm_logging_enabled", true, "deterministic", true, ...
    "hardware_independent", true, "scenario_source", "frozen_scenario_trace", ...
    "selected_input", 2, "switch_value", "0");
modes.interactive = struct( ...
    "name", "interactive", "audio_device_writer_enabled", true, ...
    "pcm_logging_enabled", false, "deterministic", false, ...
    "hardware_independent", false, "scenario_source", "dashboard_constants", ...
    "selected_input", 1, "switch_value", "1");
modes.model_binding = struct( ...
    "selection_mechanism", "Dashboard_Mode_Selector_Manual_Switch", ...
    "input_1", "Dashboard Constants", "input_2", "Qualification Scenario", ...
    "status", "REQUIRES_CONTROLLED_RUNTIME_CONFIRMATION");
end
