function controls = s12_v11_model_dashboard_controls(profile)
%S12_V11_MODEL_DASHBOARD_CONTROLS Return JSON-validated HMI declarations.
% Defaults and ranges are copied from provenance-complete profile JSON, never
% invented by the Simulink builder.

if ~isstruct(profile) || ~isscalar(profile) || ~isfield(profile, "validation") || ...
        ~isfield(profile.validation, "valid") || ~isequal(profile.validation.valid, true) || ...
        ~isfield(profile, "render_tuning") || ~isfield(profile.render_tuning, "dashboard_defaults")
    error("S12:EngineSoundV11:ModelDashboard", ...
        "Dashboard controls require a validated v1.1 JSON profile.");
end
specification = [ ...
    "rpm", "RPM"; ...
    "load", "Load"; ...
    "acceleration", "Acceleration"; ...
    "throttle", "Throttle"; ...
    "order_balance", "Order Balance"; ...
    "transient", "Transient"; ...
    "backfire_level", "Backfire Level"; ...
    "ptr_pipe_length_m", "PTR Pipe Length"; ...
    "ptr_area_m2", "PTR Area"; ...
    "ptr_reflection", "PTR Reflection"; ...
    "ptr_damping", "PTR Damping"; ...
    "gain", "Gain"];
records = profile.render_tuning.dashboard_defaults;
template = struct("field", "", "dashboard_name", "", "control_name", "", ...
    "default", 0, "range", [0, 0], "hmi_limits", [0, 0, 0]);
controls = repmat(template, 1, size(specification, 1));
for index = 1:size(specification, 1)
    field = specification(index, 1);
    if ~isfield(records, field)
        error("S12:EngineSoundV11:ModelDashboard", ...
            "Validated profile omits Dashboard record %s.", field);
    end
    record = records.(field);
    validateRecord(record, field);
    limits = double(record.range(:).');
    controls(index) = struct( ...
        "field", field, ...
        "dashboard_name", "Dashboard " + specification(index, 2), ...
        "control_name", specification(index, 2) + " Control", ...
        "default", double(record.value), ...
        "range", limits, ...
        "hmi_limits", [limits(1), (limits(2) - limits(1)) / 100, limits(2)]);
end
end

function validateRecord(record, field)
required = ["value", "unit", "range", "source_level", "source", "source_url", ...
    "source_scope", "verification_state"];
if ~isstruct(record) || ~isscalar(record)
    error("S12:EngineSoundV11:ModelDashboard", ...
        "Dashboard record %s must be a finite C/synthetic JSON record.", field);
end
actual = reshape(string(fieldnames(record)), 1, []);
if ~isequal(sort(actual), sort(required))
    error("S12:EngineSoundV11:ModelDashboard", ...
        "Dashboard record %s must be a finite C/synthetic JSON record.", field);
end
declaredRange = record.range;
if ~isnumeric(record.value) || ~isscalar(record.value) || ~isfinite(record.value) || ...
        ~isnumeric(declaredRange) || ~isvector(declaredRange) || numel(declaredRange) ~= 2
    error("S12:EngineSoundV11:ModelDashboard", ...
        "Dashboard record %s must be a finite C/synthetic JSON record.", field);
end
declaredRange = reshape(declaredRange, 1, []);
if any(~isfinite(declaredRange), "all") || declaredRange(1) > declaredRange(2) || ...
        record.value < declaredRange(1) || record.value > declaredRange(2) || ...
        string(record.source_level) ~= "C" || string(record.source) ~= "synthetic" || ...
        strlength(string(record.source_url)) ~= 0 || ...
        string(record.verification_state) ~= "synthetic_assumption"
    error("S12:EngineSoundV11:ModelDashboard", ...
        "Dashboard record %s must be a finite C/synthetic JSON record.", field);
end
end
