function contracts = s12_v11_model_contracts()
%S12_V11_MODEL_CONTRACTS Declare the eight generated Simulink wrappers.
% The wrappers are synthetic, uncalibrated, and offline.  This declaration
% is the single source of truth for model names, paths, topology, and ports.

root = fileparts(mfilename("fullpath"));
vehicleIds = s12_v11_canonical_vehicle_ids();
coreName = "S12_PTR_Radiation_Core_v11";
corePath = fullfile(root, "common", "shared_model", coreName + ".slx");
requiredChain = ["Vehicle State", "Vehicle Excitation Afterfire", ...
    "PTR Radiation Model Reference", "Stereo Renderer", "PCM Output"];
dashboardBlocks = ["Dashboard RPM", "Dashboard Load", ...
    "Dashboard Acceleration", "Dashboard Throttle", ...
    "Dashboard Order Balance", "Dashboard Transient", ...
    "Dashboard Backfire Level", "Dashboard PTR Pipe Length", ...
    "Dashboard PTR Area", "Dashboard PTR Reflection", ...
    "Dashboard PTR Damping", "Dashboard Gain"];
portContract = struct( ...
    "vehicle_state_output", "[21,1]", ...
    "excitation_output", "[960,1]", ...
    "ptr_radiation_output", "[960,1]", ...
    "pcm_output", "[960,2]", ...
    "ptr_control_output", "[4,1]", ...
    "renderer_gain_output", "[1,1]", ...
    "frame_samples", 960, ...
    "frame_period_s", 0.02, ...
    "duration_s", 90, ...
    "frame_count", 4500, ...
    "channels", 2, ...
    "afterfire_insertion_stage", "before_ptr_radiation", ...
    "post_ptr_design_permitted", false);

template = struct( ...
    "vehicle_id", "", ...
    "model_name", "", ...
    "model_path", "", ...
    "core_model_name", coreName, ...
    "core_model_path", corePath, ...
    "required_chain", requiredChain, ...
    "dashboard_blocks", dashboardBlocks, ...
    "port_contract", portContract, ...
    "pcm_size", [960,2], ...
    "synthetic", true, ...
    "uncalibrated", true, ...
    "offline", true);
contracts = repmat(template, 1, numel(vehicleIds));
for index = 1:numel(vehicleIds)
    vehicleId = vehicleIds(index);
    modelName = "S12_" + vehicleId + "_v11";
    contracts(index) = template;
    contracts(index).vehicle_id = vehicleId;
    contracts(index).model_name = modelName;
    contracts(index).model_path = fullfile(root, "vehicles", vehicleId, modelName + ".slx");
end
end
