function comparison = s12_v11_compare_audio_analysis(renderResults)
%S12_V11_COMPARE_AUDIO_ANALYSIS Compare derived synthetic pilot signatures.

if ~isstruct(renderResults) || numel(renderResults) < 2
    error("S12:EngineSoundV11:Comparison", ...
        "renderResults must contain at least two rendered profile results.");
end
profileIds = strings(1, numel(renderResults));
orderNames = "order_" + replace(compose("%.1f", 0.5:0.5:12), ".", "p");
featureNames = [orderNames, ...
    "band_20_120_hz", "band_120_500_hz", "band_500_2000_hz", "band_2000_8000_hz", ...
    "centroid_hz_normalized", "rolloff_hz_normalized", "flatness", ...
    "modulation_depth", "pulse_amplitude_cv"];
features = zeros(numel(renderResults), 24 + 4 + 5);
for index = 1:numel(renderResults)
    if ~isfield(renderResults(index), "profile_id") || ~isfield(renderResults(index), "analysis")
        error("S12:EngineSoundV11:Comparison", ...
            "Every input must expose profile_id and analysis.");
    end
    analysis = renderResults(index).analysis;
    orderSignature = mean(analysis.order_map.energy, 1);
    orderSignature = orderSignature / max(sum(orderSignature), eps);
    metrics = analysis.audio_metrics;
    if numel(orderSignature) ~= 24 || numel(metrics.band_energy_ratios) ~= 4
        error("S12:EngineSoundV11:Comparison", "Derived analysis has incompatible dimensions.");
    end
    profileIds(index) = string(renderResults(index).profile_id);
    features(index, :) = [orderSignature, metrics.band_energy_ratios, ...
        metrics.centroid_hz / 24000, metrics.rolloff_hz / 24000, ...
        metrics.flatness, metrics.modulation_depth, metrics.pulse_amplitude_cv];
end
if numel(featureNames) ~= size(features, 2)
    error("S12:EngineSoundV11:Comparison", ...
        "Every comparison feature column must have an explicit name.");
end
pairs = nchoosek(1:numel(renderResults), 2);
pairwiseDistance = zeros(size(pairs, 1), 1);
pairLabels = strings(size(pairs, 1), 1);
signatureThreshold = 0.05;
for index = 1:size(pairs, 1)
    difference = features(pairs(index, 1), 1:28) - features(pairs(index, 2), 1:28);
    pairwiseDistance(index) = sqrt(sum(difference .^ 2));
    pairLabels(index) = profileIds(pairs(index, 1)) + "__vs__" + profileIds(pairs(index, 2));
end
comparison = struct( ...
    "input_scope", "derived_synthetic_audio_analysis_only", ...
    "raw_reference_audio_used", false, ...
    "profile_ids", profileIds, ...
    "feature_names", featureNames, ...
    "features", features, ...
    "order_signature", features(:, 1:24), ...
    "band_energy_ratios", features(:, 25:28), ...
    "centroid_hz", features(:, 29) * 24000, ...
    "modulation_depth", features(:, 32), ...
    "pair_labels", pairLabels, ...
    "pairwise_distance", pairwiseDistance, ...
    "distinguishable_threshold", signatureThreshold, ...
    "distinguishable", all(pairwiseDistance > signatureThreshold));
end
