function profiles = s12_engine_sound_list_profiles()
%S12_ENGINE_SOUND_LIST_PROFILES Compatibility entry point for v1.1 only.
% This local wrapper intentionally exposes only canonical v1.1 synthetic IDs;
% it never mutates or implicitly routes into the frozen v1.0 implementation.

listed = s12_v11_list_profiles();
template = struct("id", "", "profile_id", "", "make", "", "model", "", ...
    "cylinders", 0, "pilot", false, "render_supported", false, "synthetic", true);
profiles = repmat(template, 1, numel(listed));
for index = 1:numel(listed)
    profile = s12_v11_load_profile(listed(index).profile_id);
    profiles(index) = struct( ...
        "id", listed(index).profile_id, ...
        "profile_id", listed(index).profile_id, ...
        "make", listed(index).make, ...
        "model", listed(index).model, ...
        "cylinders", profile.character.cylinders, ...
        "pilot", listed(index).pilot, ...
        "render_supported", listed(index).render_supported, ...
        "synthetic", true);
end
end
