function profile = s12_v11_load_profile(identifier)
%S12_V11_LOAD_PROFILE Load one validated synthetic v1.1 vehicle package.
% Every render-affecting literal originates in profile.json render_tuning.

identifier = s12_v11_validate_canonical_vehicle_id(identifier);
root = fileparts(mfilename("fullpath"));
common = fullfile(root, "common");
if isempty(which("s12_v11_validate_vehicle_package"))
    addpath(common);
end
packageRoot = fullfile(root, "vehicles", identifier);
if ~isfolder(packageRoot)
    error("S12:EngineSoundV11:ProfileNotFound", "Unknown v1.1 vehicle package: %s", identifier);
end
validation = s12_v11_validate_vehicle_package(packageRoot);
metadata = jsondecode(fileread(fullfile(packageRoot, "profile.json")));
targets = jsondecode(fileread(fullfile(packageRoot, "acoustic_targets.json")));
afterfireMetadata = jsondecode(fileread(fullfile(packageRoot, "afterfire_profile.json")));
referenceManifest = jsondecode(fileread(fullfile(packageRoot, "reference_manifest.json")));
tuning = mapRenderTuning(metadata.render_tuning);
engine = mapEngineEventMap(metadata.engine);
profile = struct( ...
    "schema_version", "s12-engine-sound-v11-render-1", ...
    "vehicle_id", identifier, ...
    "synthetic", true, ...
    "uncalibrated", true, ...
    "offline", true, ...
    "non_oem", true, ...
    "validation", validation, ...
    "metadata", metadata, ...
    "acoustic_targets", targets, ...
    "afterfire_metadata", afterfireMetadata, ...
    "reference_manifest", referenceManifest, ...
    "engine", engine, ...
    "architecture", tuning.architecture, ...
    "character", tuning.character, ...
    "transient", tuning.transient, ...
    "afterfire", tuning.afterfire, ...
    "ptr", tuning.ptr, ...
    "renderer", tuning.renderer, ...
    "dashboard_defaults", tuning.dashboard_defaults, ...
    "vehicle_state", tuning.vehicle_state);
profile.render_tuning = metadata.render_tuning;
end

function engine = mapEngineEventMap(metadataEngine)
% Keep the event geometry JSON-owned and derive each source frame from it.
engine = struct( ...
    "configuration", string(valueOf(metadataEngine.configuration)), ...
    "layout", string(valueOf(metadataEngine.layout)), ...
    "firing_order", reshape(double(valueOf(metadataEngine.firing_order)), 1, []), ...
    "firing_phases_deg", reshape(double(valueOf(metadataEngine.firing_phases_deg)), 1, []), ...
    "bank_map", reshape(double(valueOf(metadataEngine.bank_map)), 1, []), ...
    "redline_rpm", double(valueOf(metadataEngine.redline_rpm)), ...
    "ecu_logic", string(valueOf(metadataEngine.ecu_logic)));
end

function tuning = mapRenderTuning(renderTuning)
architecture = renderTuning.architecture;
rpmLoad = renderTuning.rpm_load;
orderHarmonics = renderTuning.order_harmonics;
characterParameters = renderTuning.character;
tuning = struct();
tuning.architecture = struct( ...
    "engine_kind", string(valueOf(architecture.engine_kind)), ...
    "cylinders", valueOf(architecture.cylinders), ...
    "rotor_count", valueOf(architecture.rotor_count), ...
    "chambers_per_rotor", valueOf(architecture.chambers_per_rotor), ...
    "shaft_turns_per_rotor_turn", valueOf(architecture.shaft_turns_per_rotor_turn));
tuning.character = struct( ...
    "engine_kind", tuning.architecture.engine_kind, ...
    "cylinders", tuning.architecture.cylinders, ...
    "idle_rpm", valueOf(rpmLoad.idle_rpm), ...
    "redline_rpm", valueOf(rpmLoad.redline_rpm), ...
    "minimum_load", valueOf(rpmLoad.minimum_load), ...
    "maximum_load", valueOf(rpmLoad.maximum_load), ...
    "order_gains", reshape(valueOf(orderHarmonics.order_gains), 1, []), ...
    "firing_gain", valueOf(orderHarmonics.firing_gain), ...
    "firing_harmonic_gain", valueOf(orderHarmonics.firing_harmonic_gain), ...
    "pulse_sharpness", valueOf(characterParameters.pulse_sharpness), ...
    "intake_tone", valueOf(characterParameters.intake_tone), ...
    "supercharger_tone", valueOf(characterParameters.supercharger_tone), ...
    "source_gain", valueOf(characterParameters.source_gain), ...
    "output_gain", valueOf(characterParameters.output_gain), ...
    "stereo_offset", valueOf(characterParameters.stereo_offset), ...
    "order_load_tilt_gain", valueOf(characterParameters.order_load_tilt_gain), ...
    "intake_base_mix", valueOf(characterParameters.intake_base_mix), ...
    "intake_throttle_mix", valueOf(characterParameters.intake_throttle_mix), ...
    "supercharger_base_mix", valueOf(characterParameters.supercharger_base_mix), ...
    "supercharger_throttle_mix", valueOf(characterParameters.supercharger_throttle_mix), ...
    "source_base_mix", valueOf(characterParameters.source_base_mix), ...
    "source_load_mix", valueOf(characterParameters.source_load_mix), ...
    "rotary_apex_gain", valueOf(characterParameters.rotary_apex_gain), ...
    "rotor_count", tuning.architecture.rotor_count, ...
    "chambers_per_rotor", tuning.architecture.chambers_per_rotor, ...
    "shaft_turns_per_rotor_turn", tuning.architecture.shaft_turns_per_rotor_turn);
tuning.transient = unwrapSection(renderTuning.transient);
tuning.afterfire = unwrapSection(renderTuning.afterfire);
tuning.afterfire.refractory_jitter_fraction = valueOf( ...
    renderTuning.afterfire.refractory_jitter_fraction);
tuning.ptr = unwrapSection(renderTuning.ptr);
tuning.renderer = unwrapSection(renderTuning.renderer);
tuning.dashboard_defaults = unwrapSection(renderTuning.dashboard_defaults);
tuning.vehicle_state = unwrapSection(renderTuning.vehicle_state);
end

function values = unwrapSection(section)
names = string(fieldnames(section));
values = struct();
for index = 1:numel(names)
    name = names(index);
    values.(name) = valueOf(section.(name));
end
end

function value = valueOf(record)
if ~isstruct(record) || ~isscalar(record) || ~isfield(record, "value")
    error("S12:EngineSoundV11:RenderTuning", "Validated tuning records must contain one value field.");
end
value = record.value;
end
