function [schedule] = s12_v11_rotary_event_frequency(character, rpm)
%S12_V11_ROTARY_EVENT_FREQUENCY Return a synthetic two-rotor event schedule.
% The schedule is intentionally derived from rotor chamber geometry and the
% eccentric-shaft ratio; it never maps a rotary engine through a piston
% cylinders/2 firing-frequency law.  All values are synthetic assumptions.

if ~isstruct(character) || ~isscalar(character) || ...
        ~isfield(character, "engine_kind") || string(character.engine_kind) ~= "rotary"
    error("S12:EngineSoundV11:RotaryCharacter", ...
        "Rotary event scheduling requires one rotary character contract.");
end
required = ["rotor_count", "chambers_per_rotor", "shaft_turns_per_rotor_turn"];
for field = required
    if ~isfield(character, field) || ~isnumeric(character.(field)) || ...
            ~isscalar(character.(field)) || ~isfinite(character.(field)) || ...
            character.(field) <= 0
        error("S12:EngineSoundV11:RotaryCharacter", ...
            "Rotary character.%s must be one positive finite scalar.", field);
    end
end
if ~isnumeric(rpm) || ~isscalar(rpm) || ~isfinite(rpm) || rpm < 0
    error("S12:EngineSoundV11:RotaryRpm", "rpm must be one nonnegative finite scalar.");
end

shaftFrequencyHz = double(rpm) / 60;
rotorCount = double(character.rotor_count);
chambersPerRotor = double(character.chambers_per_rotor);
shaftTurnsPerRotorTurn = double(character.shaft_turns_per_rotor_turn);
combustionEventHz = shaftFrequencyHz * rotorCount * chambersPerRotor / ...
    shaftTurnsPerRotorTurn;
apexPassHz = shaftFrequencyHz * rotorCount;
schedule = struct( ...
    "event_model", "synthetic_rotary_chamber_scheduler", ...
    "rotor_count", rotorCount, ...
    "chambers_per_rotor", chambersPerRotor, ...
    "shaft_turns_per_rotor_turn", shaftTurnsPerRotorTurn, ...
    "shaft_frequency_hz", shaftFrequencyHz, ...
    "combustion_event_hz", combustionEventHz, ...
    "apex_pass_hz", apexPassHz, ...
    "source_level", "C", ...
    "source", "synthetic");
end
