function result = s12_v11_render_profile(profileInput, varargin)
%S12_V11_RENDER_PROFILE Render deterministic synthetic stereo PCM in memory.

profile = resolveProfile(profileInput);
parser = inputParser;
parser.addParameter("AfterfireLevel", "subtle");
parser.addParameter("FrameIndices", []);
parser.addParameter("ScenarioKey", "s12-v11-default");
parser.parse(varargin{:});
afterfireLevel = validateChoice(parser.Results.AfterfireLevel, ...
    ["off", "subtle", "aggressive"], "AfterfireLevel");
scenarioKey = validateText(parser.Results.ScenarioKey, "ScenarioKey");
cycle = s12_v11_compile_vehicle_cycle(profile);
frameIndices = validateFrameIndices(parser.Results.FrameIndices, cycle.frame_count);
common = fullfile(fileparts(mfilename("fullpath")), "common");
if isempty(which("s12_v11_apply_afterfire_before_ptr"))
    addpath(common);
end
[cycleAfterfireEvents, afterfireSchedule] = s12_v11_compile_afterfire_schedule( ...
    cycle, profile, afterfireLevel, scenarioKey);

sampleRateHz = profile.renderer.sample_rate_hz;
frameSamples = profile.renderer.frame_samples;
channels = profile.renderer.channels;
bitsPerSample = profile.renderer.bits_per_sample;
if channels ~= 2 || bitsPerSample ~= 24 || profile.renderer.hard_limiter
    error("S12:EngineSoundV11:Renderer", ...
        "Validated v1.1 renderer tuning must remain 24-bit stereo without a hard limiter.");
end
pcm = zeros(numel(frameIndices) * frameSamples, channels);
baseExcitation = zeros(numel(frameIndices) * frameSamples, 1);
startupSourceExcitation = zeros(numel(frameIndices) * frameSamples, 1);
prePtrExcitation = zeros(numel(frameIndices) * frameSamples, 1);
context = [];
eventTemplate = struct("time_s", 0, "kind", "", ...
    "location", "pre_ptr_exhaust_source", "energy", 0, ...
    "cluster_id", "", "variation", 0, "eligibility_explanation", "", ...
    "dynamic_energy_scale", 1, "lift_duration_s", 0);
allEvents = repmat(eventTemplate, 0, 1);
diagnosticTemplate = struct( ...
    "frame_index", 0, ...
    "phase_start_rad", zeros(1, 9), ...
    "phase_next_rad", zeros(1, 9), ...
    "frame_samples", frameSamples, ...
    "channels", channels, ...
    "event_count", 0, ...
    "startup_stage", "engine_excitation_before_ptr_radiation", ...
    "startup_applied", false, ...
    "pre_ptr_changed", false, ...
    "insertion_stage", "before_ptr_radiation", ...
    "post_pcm_append", false);
frameDiagnostics = repmat(diagnosticTemplate, numel(frameIndices), 1);

for position = 1:numel(frameIndices)
    frameIndex = frameIndices(position);
    state = table2struct(cycle.state(frameIndex, :));
    state.timestamp_s = cycle.timestamp_s(frameIndex);
    [baseFrame, context, phaseDiagnostics] = renderExcitationFrame( ...
        profile, state, context, sampleRateHz, frameSamples);
    [sourceFrame, startupDiagnostics] = s12_v11_apply_startup_source_envelope( ...
        baseFrame, state.timestamp_s, sampleRateHz);
    eventsForPressure = selectEventsForPressureFrame(cycleAfterfireEvents, ...
        state.timestamp_s, sampleRateHz, frameSamples);
    events = selectEventsStartingInFrame(cycleAfterfireEvents, ...
        state.timestamp_s, sampleRateHz, frameSamples);
    [afterfireFrame, ~] = s12_v11_render_afterfire_pressure_frame(eventsForPressure, ...
        state.timestamp_s, sampleRateHz, frameSamples, ...
        scenarioKey);
    [pressureFrame, ptrDiagnostics] = s12_v11_apply_afterfire_before_ptr( ...
        sourceFrame, afterfireFrame, profile.ptr.pipe_length_m, profile.ptr.area_m2, ...
        profile.ptr.reflection, profile.ptr.damping, position == 1);
    framePcm = profile.character.output_gain * [ ...
        pressureFrame, (1 - profile.character.stereo_offset) * pressureFrame];
    if ~isequal(size(framePcm), [frameSamples, channels])
        error("S12:EngineSoundV11:FrameContract", ...
            "Every rendered frame must match the validated renderer frame/channel contract.");
    end
    peak = max(abs(framePcm), [], "all");
    if any(~isfinite(framePcm), "all") || peak >= 1
        error("S12:EngineSoundV11:AudioSafety", ...
            "Synthetic PCM must remain finite with peak strictly below 1.");
    end
    samples = (position - 1) * frameSamples + (1:frameSamples);
    pcm(samples, :) = framePcm;
    baseExcitation(samples) = baseFrame;
    startupSourceExcitation(samples) = sourceFrame;
    prePtrExcitation(samples) = ptrDiagnostics.pre_ptr_excitation;
    if ~isempty(events)
        allEvents(end + (1:numel(events)), 1) = events; %#ok<AGROW>
    end
    frameDiagnostics(position) = struct( ...
        "frame_index", frameIndex, ...
        "phase_start_rad", phaseDiagnostics.phase_start_rad, ...
        "phase_next_rad", phaseDiagnostics.phase_next_rad, ...
        "frame_samples", frameSamples, ...
        "channels", channels, ...
        "event_count", numel(events), ...
        "startup_stage", startupDiagnostics.stage, ...
        "startup_applied", startupDiagnostics.applied, ...
        "pre_ptr_changed", ptrDiagnostics.pre_ptr_changed, ...
        "insertion_stage", "before_ptr_radiation", ...
        "post_pcm_append", false);
end
if any(~isfinite(pcm), "all") || max(abs(pcm), [], "all") >= 1
    error("S12:EngineSoundV11:AudioSafety", ...
        "Rendered PCM violated the finite non-clipping contract.");
end
trace = cycle.state(frameIndices, :);
trace = addvars(trace, cycle.timestamp_s(frameIndices), Before=1, ...
    NewVariableNames="timestamp_s");
analysis = s12_v11_analyze_sound(pcm, trace, allEvents, sampleRateHz);
result = struct( ...
    "schema_version", "s12-engine-sound-v11-render-1", ...
    "profile_id", profile.vehicle_id, ...
    "synthetic", true, ...
    "sample_rate_hz", sampleRateHz, ...
    "frame_samples", frameSamples, ...
    "bits_per_sample", bitsPerSample, ...
    "frame_indices", frameIndices, ...
    "afterfire_level", afterfireLevel, ...
    "pcm", pcm, ...
    "pcm_sha256", sha256Pcm(pcm), ...
    "base_excitation", baseExcitation, ...
    "startup_source_excitation", startupSourceExcitation, ...
    "pre_ptr_excitation", prePtrExcitation, ...
    "events", allEvents, ...
    "afterfire_schedule", afterfireSchedule, ...
    "trace", trace, ...
    "analysis", analysis, ...
    "frame_diagnostics", frameDiagnostics);
end

function events = selectEventsForPressureFrame(allEvents, frameStartS, sampleRateHz, frameSamples)
if isempty(allEvents)
    events = allEvents;
    return;
end
tailDurationS = 0.012;
frameEndS = frameStartS + frameSamples / sampleRateHz;
times = [allEvents.time_s];
keep = times >= frameStartS - tailDurationS & times < frameEndS;
events = allEvents(keep);
end

function events = selectEventsStartingInFrame(allEvents, frameStartS, sampleRateHz, frameSamples)
if isempty(allEvents)
    events = allEvents;
    return;
end
frameEndS = frameStartS + frameSamples / sampleRateHz;
times = [allEvents.time_s];
events = allEvents(times >= frameStartS & times < frameEndS);
end

function profile = resolveProfile(value)
if isstruct(value) && isscalar(value) && isfield(value, "vehicle_id") && isfield(value, "character")
    profile = value;
else
    profile = s12_v11_load_profile(value);
end
end

function frameIndices = validateFrameIndices(value, frameCount)
if isempty(value)
    frameIndices = 1:frameCount;
    return;
end
if ~isnumeric(value) || ~isvector(value) || any(~isfinite(value)) || ...
        any(value ~= floor(value)) || any(value < 1) || any(value > frameCount)
    error("S12:EngineSoundV11:FrameIndices", ...
        "FrameIndices must contain valid integer cycle positions.");
end
frameIndices = reshape(double(value), 1, []);
end

function value = validateChoice(value, choices, name)
value = lower(validateText(value, name));
if ~ismember(value, choices)
    error("S12:EngineSoundV11:Option", "%s must be one of: %s.", name, strjoin(choices, ", "));
end
end

function value = validateText(value, name)
if ~((ischar(value) && isrow(value)) || (isstring(value) && isscalar(value))) || ...
        strlength(string(value)) == 0
    error("S12:EngineSoundV11:Option", "%s must be one nonempty text scalar.", name);
end
value = string(value);
end

function [excitation, context, diagnostics] = renderExcitationFrame( ...
        profile, state, context, sampleRateHz, frameSamples)
character = profile.character;
if isempty(context)
    context = struct( ...
        "phase_rad", zeros(1, 6), ...
        "firing_phase_rad", 0, ...
        "intake_phase_rad", 0, ...
        "supercharger_phase_rad", 0, ...
        "last_throttle", state.throttle);
end
phaseStart = [context.phase_rad, context.firing_phase_rad, ...
    context.intake_phase_rad, context.supercharger_phase_rad];
rpm = max(character.idle_rpm, min(character.redline_rpm, double(state.rpm)));
loadValue = max(character.minimum_load, min(character.maximum_load, double(state.load)));
throttle = max(0, min(1, double(state.throttle)));
timeIndex = (0:frameSamples - 1).';
baseFrequency = rpm / 60;
excitation = zeros(frameSamples, 1);
for order = 1:numel(character.order_gains)
    omega = 2 * pi * baseFrequency * order / sampleRateHz;
    phase = context.phase_rad(order) + omega * timeIndex;
    tilt = 1 + character.order_load_tilt_gain * loadValue * (order - 1) / ...
        max(numel(character.order_gains) - 1, 1);
    excitation = excitation + character.order_gains(order) * tilt .* sin(phase);
    context.phase_rad(order) = mod(context.phase_rad(order) + omega * frameSamples, 2 * pi);
end
if character.engine_kind == "rotary"
    [rotaryExcitation, context.firing_phase_rad, firingPhase] = ...
        s12_v11_render_rotary_excitation_frame(state, character, profile.engine, ...
        context.firing_phase_rad, sampleRateHz, frameSamples);
    excitation = excitation + rotaryExcitation;
else
    % Shared helper consumes character.firing_gain and character.firing_harmonic_gain
    % with the JSON-owned profile.engine firing-event geometry.
    [pistonExcitation, context.firing_phase_rad, firingPhase] = ...
        s12_v11_render_piston_excitation_frame(state, character, profile.engine, ...
        context.firing_phase_rad, sampleRateHz, frameSamples);
    excitation = excitation + pistonExcitation;
end
intakeOmega = 2 * pi * 0.5 * baseFrequency / sampleRateHz;
excitation = excitation + character.intake_tone * ...
    (character.intake_base_mix + character.intake_throttle_mix * throttle) .* ...
    sin(context.intake_phase_rad + intakeOmega * timeIndex);
context.intake_phase_rad = mod(context.intake_phase_rad + intakeOmega * frameSamples, 2 * pi);
if character.supercharger_tone > 0
    superchargerOmega = 2 * pi * 10 * baseFrequency / sampleRateHz;
    excitation = excitation + character.supercharger_tone * ...
        (character.supercharger_base_mix + character.supercharger_throttle_mix * throttle) .* ...
        sin(context.supercharger_phase_rad + superchargerOmega * timeIndex);
    context.supercharger_phase_rad = mod( ...
        context.supercharger_phase_rad + superchargerOmega * frameSamples, 2 * pi);
end
transient = max(double(state.acceleration), 0) * profile.transient.acceleration_gain + ...
    profile.transient.throttle_delta_gain * abs(throttle - context.last_throttle);
context.last_throttle = throttle;
excitation = character.source_gain * ...
    (character.source_base_mix + character.source_load_mix * loadValue) .* excitation + ...
    profile.transient.output_gain * transient .* sin(2 * firingPhase);
if any(~isfinite(excitation)) || ~isequal(size(excitation), [frameSamples, 1])
    error("S12:EngineSoundV11:Excitation", ...
        "Base excitation must be one finite [960,1] pressure-source frame.");
end
phaseNext = [context.phase_rad, context.firing_phase_rad, ...
    context.intake_phase_rad, context.supercharger_phase_rad];
diagnostics = struct("phase_start_rad", phaseStart, "phase_next_rad", phaseNext);
end

function hash = sha256Pcm(pcm)
bytes = typecast(single(pcm(:)), "uint8");
digest = java.security.MessageDigest.getInstance("SHA-256");
digest.update(bytes);
hash = lower(join(compose("%02x", typecast(digest.digest(), "uint8")), ""));
end
