function comparison = s12_engine_sound_compare_reference(profileInput)
%S12_ENGINE_SOUND_COMPARE_REFERENCE Return bounded, derived v1.1 reference state.
% v1.1 has no licensed/raw reference capture, so no waveform is read or copied.

profile = s12_v11_load_profile(s12_v11_validate_canonical_vehicle_id(profileInput));
comparison = struct( ...
    "profile_id", profile.vehicle_id, ...
    "synthetic", true, ...
    "uncalibrated", true, ...
    "reference_audio_state", "not_acquired", ...
    "comparison_state", "pending_rpm_or_crank_angle_synchronized_reference_analysis", ...
    "raw_reference_audio_used", false, ...
    "acoustic_targets", profile.acoustic_targets, ...
    "reference_manifest", profile.reference_manifest);
end
