pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

def app1OboeRepo = gradle.startParameter.projectProperties.get("app1OboeRepo")

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        if (app1OboeRepo != null) {
            maven {
                url = uri(app1OboeRepo)
                content {
                    includeGroup("com.google.oboe")
                    includeGroup("com.google.prefab")
                }
            }
        }
        google()
        mavenCentral()
    }
}

rootProject.name = "S12AndroidVehicleSoundDemo"
include(":app")
include(":player")
