const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function setup(){const nodes={},calls=[];for(const id of ['mount-axis','mount-parked','mount-confirm','mount-moved','mount-status','mount-summary'])nodes[id]={value:'',checked:false,disabled:false,textContent:'',listeners:{},addEventListener(n,f){this.listeners[n]=f}};const c={window:{AndroidBridge:{confirmMounting:(...a)=>calls.push(['confirm',...a]),invalidateMounting:()=>calls.push(['invalidate'])}},document:{readyState:'complete',getElementById:id=>nodes[id]||null}};vm.createContext(c);vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../../Project/android/app/src/main/assets/mounting-ui.js'),'utf8'),c);return {nodes,calls,update:m=>c.window.VicoMounting.update({mounting:m})};}
const ready={selected:'TOP',trusted:false,reason:'CONFIRM_FIXED_MOUNT',requestRevision:1,result:'IDLE',naturalPortrait:true,calibrated:true,canConfirm:true,moving:false};
test('no automatic selection or confirmation writes',()=>{const t=setup();t.update({...ready,selected:''});assert.equal(t.nodes['mount-axis'].value,'');assert.equal(t.nodes['mount-confirm'].disabled,true);assert.deepEqual(t.calls,[])});
test('requires explicit choice and parked acknowledgement then suppresses duplicate pending clicks',()=>{const t=setup();t.update(ready);t.nodes['mount-axis'].value='SCREEN';t.nodes['mount-axis'].listeners.change();t.nodes['mount-parked'].checked=true;t.nodes['mount-parked'].listeners.change();t.nodes['mount-confirm'].listeners.click();t.nodes['mount-confirm'].listeners.click();assert.deepEqual(t.calls,[['confirm','SCREEN',true]]);t.update(ready);assert.equal(t.nodes['mount-axis'].value,'SCREEN');t.update({...ready,requestRevision:2,result:'CONFIRMED',selected:'SCREEN',trusted:true});assert.equal(t.nodes['mount-confirm'].disabled,false)});
test('new render ticks do not overwrite an unsaved choice',()=>{const t=setup();t.update(ready);t.nodes['mount-axis'].value='LEFT';t.nodes['mount-axis'].listeners.change();t.update(ready);assert.equal(t.nodes['mount-axis'].value,'LEFT')});
test('background trust loss requires new parked acknowledgement but retains selection',()=>{const t=setup();t.update({...ready,trusted:true});t.nodes['mount-parked'].checked=true;t.update({...ready,reason:'APP_BACKGROUND'});assert.equal(t.nodes['mount-axis'].value,'TOP');assert.equal(t.nodes['mount-parked'].checked,false);assert.match(t.nodes['mount-status'].textContent,/无需重新校准/)});
test('moving state disables setup without opening dialogs',()=>{const t=setup();t.update({...ready,moving:true,canConfirm:false});assert.equal(t.nodes['mount-axis'].disabled,true);assert.equal(t.nodes['mount-confirm'].disabled,true);assert.match(t.nodes['mount-status'].textContent,/安全停车/);assert.deepEqual(t.calls,[])});
test('manual phone moved only invalidates and never edits saved preference',()=>{const t=setup();t.update({...ready,trusted:true});t.nodes['mount-moved'].listeners.click();assert.deepEqual(t.calls,[['invalidate']])});
