function [pressure, diagnostics] = s12_v11_apply_afterfire_before_ptr(baseExcitation, afterfirePressure, pipeLengthM, areaM2, reflection, damping, reset)
%S12_V11_APPLY_AFTERFIRE_BEFORE_PTR Inject afterfire into the PTR input only.
% The unchanged shared adapter remains the sole PTR/Radiation call boundary.

validateExcitationInputs(baseExcitation, afterfirePressure);
validatePtrInputs(pipeLengthM, areaM2, reflection, damping, reset);
adapter = resolveCanonicalAdapter();
addpath(adapter.source_folder, "-begin");
resolvedPath = string(which(adapter.function_name));
if resolvedPath ~= adapter.source_path
    error("S12:EngineSoundV11:SharedAdapter", ...
        "The resolved PTR adapter is not the verified canonical frozen source.");
end

prePtrExcitation = baseExcitation + afterfirePressure;
pressure = s12_sound_playground_ptr_tuning_step(prePtrExcitation, pipeLengthM, ...
    areaM2, reflection, damping, reset);
if ~isnumeric(pressure) || ~isequal(size(pressure), size(baseExcitation)) || ...
        any(~isfinite(pressure), "all")
    error("S12:EngineSoundV11:SharedAdapter", ...
        "The existing PTR adapter must return one finite pressure frame matching its input.");
end

diagnostics = struct( ...
    "base_excitation", baseExcitation, ...
    "afterfire_pressure", afterfirePressure, ...
    "pre_ptr_excitation", prePtrExcitation, ...
    "pre_ptr_changed", any(prePtrExcitation ~= baseExcitation, "all"), ...
    "ptr_function", "s12_sound_playground_ptr_tuning_step", ...
    "ptr_source_path", adapter.source_path, ...
    "ptr_source_sha256", adapter.sha256, ...
    "ptr_expected_sha256", adapter.expected_sha256, ...
    "ptr_called", true, ...
    "ptr_input_contract", ["excitation", "pipeLengthM", "areaM2", ...
        "reflection", "damping", "reset"], ...
    "insertion_stage", "before_ptr_radiation", ...
    "post_pcm_append", false, ...
    "causality_chain", ["base_excitation", "afterfire_pressure", ...
        "pre_ptr_excitation", "ptr_radiation_pressure"]);
end

function adapter = resolveCanonicalAdapter()
persistent cachedAdapter
if ~isempty(cachedAdapter)
    adapter = cachedAdapter;
    return;
end
v11Root = fileparts(fileparts(mfilename("fullpath")));
resolverPath = fullfile(v11Root, "s12_v11_resolve_frozen_ptr_adapter.m");
if ~isfile(resolverPath)
    error("S12:EngineSoundV11:SharedAdapter", ...
        "The v1.1 canonical PTR adapter resolver is missing.");
end
addpath(v11Root, "-begin");
if string(which("s12_v11_resolve_frozen_ptr_adapter")) ~= string(resolverPath)
    error("S12:EngineSoundV11:SharedAdapter", ...
        "The v1.1 PTR adapter resolver did not resolve from its canonical source.");
end
adapter = s12_v11_resolve_frozen_ptr_adapter();
cachedAdapter = adapter;
end

function validateExcitationInputs(baseExcitation, afterfirePressure)
if ~isnumeric(baseExcitation) || ~isvector(baseExcitation) || isempty(baseExcitation) || ...
        any(~isfinite(baseExcitation), "all")
    error("S12:EngineSoundV11:SharedAdapter", ...
        "baseExcitation must be one nonempty finite numeric frame.");
end
if ~isnumeric(afterfirePressure) || ~isvector(afterfirePressure) || ...
        ~isequal(size(afterfirePressure), size(baseExcitation)) || ...
        any(~isfinite(afterfirePressure), "all")
    error("S12:EngineSoundV11:SharedAdapter", ...
        "afterfirePressure must be finite and match baseExcitation exactly.");
end
end

function validatePtrInputs(pipeLengthM, areaM2, reflection, damping, reset)
values = [pipeLengthM, areaM2, reflection, damping];
if ~isnumeric(values) || numel(values) ~= 4 || any(~isfinite(values)) || ...
        pipeLengthM <= 0 || areaM2 <= 0 || abs(reflection) > 1 || damping < 0 || damping >= 1
    error("S12:EngineSoundV11:SharedAdapter", ...
        "PTR parameters must satisfy the existing adapter's finite bounded contract.");
end
if ~isscalar(reset) || ...
        ~(islogical(reset) || (isnumeric(reset) && isfinite(reset) && ismember(reset, [0, 1])))
    error("S12:EngineSoundV11:SharedAdapter", "reset must be one logical value.");
end
end
