function [events, diagnostics] = s12_v11_compile_afterfire_schedule( ...
        cycle, profile, afterfireLevel, scenarioKey)
%S12_V11_COMPILE_AFTERFIRE_SCHEDULE Compile one deterministic whole-cycle schedule.
% This is the only non-Simulink renderer scheduling path. It advances one
% scheduler state over continuous timestamps rather than restarting per frame.

validateCycle(cycle);
eventTemplate = struct("time_s", 0, "kind", "", ...
    "location", "pre_ptr_exhaust_source", "energy", 0, ...
    "cluster_id", "", "variation", 0, "eligibility_explanation", "", ...
    "dynamic_energy_scale", 1, "lift_duration_s", 0);
events = repmat(eventTemplate, 0, 1);
schedulerState = [];
clusterStarts = zeros(0, 1);
frameDiagnostics = cell(cycle.frame_count, 1);
for frameIndex = 1:cycle.frame_count
    state = table2struct(cycle.state(frameIndex, :));
    state.timestamp_s = double(cycle.timestamp_s(frameIndex));
    [frameEvents, frameDiagnostics{frameIndex}, schedulerState] = ...
        s12_v11_schedule_afterfire(state, profile, afterfireLevel, scenarioKey, schedulerState);
    if ~isempty(frameEvents)
        events(end + (1:numel(frameEvents)), 1) = frameEvents; %#ok<AGROW>
    end
    if frameDiagnostics{frameIndex}.cluster_started
        clusterStarts(end + 1, 1) = frameEvents(1).time_s; %#ok<AGROW>
    end
end
diagnostics = struct( ...
    "schema_version", "s12-v11-afterfire-cycle-schedule-1", ...
    "frame_count", cycle.frame_count, ...
    "event_count", numel(events), ...
    "cluster_count", numel(clusterStarts), ...
    "cluster_start_times_s", clusterStarts, ...
    "scheduler_state", schedulerState, ...
    "frame_diagnostics", {frameDiagnostics}, ...
    "insertion_stage", "before_ptr_radiation", ...
    "post_pcm_append", false, ...
    "causality_chain", ["continuous_vehicle_state", "eligibility", ...
        "stateful_events", "pre_ptr_pressure_excitation", "ptr_radiation"]);
end

function validateCycle(cycle)
if ~isstruct(cycle) || ~isscalar(cycle) || ...
        ~isfield(cycle, "frame_count") || ~isfield(cycle, "timestamp_s") || ...
        ~isfield(cycle, "state")
    error("S12:EngineSoundV11:AfterfireCycle", ...
        "cycle must contain frame_count, timestamp_s, and state.");
end
if ~istable(cycle.state) || height(cycle.state) ~= cycle.frame_count || ...
        numel(cycle.timestamp_s) ~= cycle.frame_count
    error("S12:EngineSoundV11:AfterfireCycle", ...
        "cycle state and timestamp dimensions must match frame_count.");
end
timestamps = double(cycle.timestamp_s(:));
if any(~isfinite(timestamps)) || any(diff(timestamps) <= 0)
    error("S12:EngineSoundV11:AfterfireCycle", ...
        "cycle timestamps must be finite and strictly increasing.");
end
end
