[platformio]
default_envs = esp32s3dev

[env]
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Wno-unused-parameter

[env:esp32s3dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags =
    ${env.build_flags}
    -DBOARD_ESP32S3
lib_deps =
    pschatzmann/arduino-audio-tools
    h2zero/NimBLE-Arduino
    bblanchon/ArduinoJson

[env:native]
platform = native
test_framework = unity
test_filter = native/*
test_build_src = no
build_flags =
    ${env.build_flags}
    -DNATIVE_TEST
